"""
NexERP Inventory Enums.
"""

from enum import Enum


class ItemType(str, Enum):
    RAW_MATERIAL = "RAW_MATERIAL"
    WORK_IN_PROGRESS = "WORK_IN_PROGRESS"
    FINISHED_GOOD = "FINISHED_GOOD"
    SERVICE = "SERVICE"
    CONSUMABLE = "CONSUMABLE"


class ValuationMethod(str, Enum):
    FIFO = "FIFO"
    MOVING_AVERAGE = "MOVING_AVERAGE"
    STANDARD_COST = "STANDARD_COST"


class MovementType(str, Enum):
    GOODS_RECEIPT = "GOODS_RECEIPT"
    GOODS_ISSUE = "GOODS_ISSUE"
    WAREHOUSE_TRANSFER = "WAREHOUSE_TRANSFER"
    LOCATION_TRANSFER = "LOCATION_TRANSFER"
    ADJUSTMENT_POSITIVE = "ADJUSTMENT_POSITIVE"
    ADJUSTMENT_NEGATIVE = "ADJUSTMENT_NEGATIVE"
    PRODUCTION_CONSUMPTION = "PRODUCTION_CONSUMPTION"
    PRODUCTION_OUTPUT = "PRODUCTION_OUTPUT"
    CYCLE_COUNT_ADJUSTMENT = "CYCLE_COUNT_ADJUSTMENT"


class CycleCountStatus(str, Enum):
    DRAFT = "DRAFT"
    IN_PROGRESS = "IN_PROGRESS"
    APPROVED = "APPROVED"
    CANCELLED = "CANCELLED"
