"""
Audit & Compliance Enums.
"""
import enum

class AuditFindingSeverity(str, enum.Enum):
    DEFICIENCY_LOW = "DEFICIENCY_LOW"
    SIGNIFICANT_DEFICIENCY = "SIGNIFICANT_DEFICIENCY"
    MATERIAL_WEAKNESS = "MATERIAL_WEAKNESS"

class SamplingMethodology(str, enum.Enum):
    RANDOM_STATISTICAL = "RANDOM_STATISTICAL"
    MONETARY_UNIT_SAMPLING_MUS = "MONETARY_UNIT_SAMPLING_MUS"
    STRATIFIED_HIGH_VALUE = "STRATIFIED_HIGH_VALUE"
    TARGETED_HIGH_RISK = "TARGETED_HIGH_RISK"
