"""
Advanced Planning & Scheduling (APS) Enums.
"""
import enum

class WorkCenterConstraintType(str, enum.Enum):
    FINITE_MACHINE_HOURS = "FINITE_MACHINE_HOURS"
    SPECIALIZED_LABOR_OPERATOR = "SPECIALIZED_LABOR_OPERATOR"
    TOOLING_DIE_AVAILABILITY = "TOOLING_DIE_AVAILABILITY"
    CURING_DRYING_BUFFER = "CURING_DRYING_BUFFER"

class ScheduleOptimizationCriterion(str, enum.Enum):
    MINIMIZE_MAKESPAN = "MINIMIZE_MAKESPAN"
    MINIMIZE_CHANGEOVER_TIME = "MINIMIZE_CHANGEOVER_TIME"
    MAXIMIZE_ON_TIME_DELIVERY = "MAXIMIZE_ON_TIME_DELIVERY"
    BALANCED_LOAD_LEVELING = "BALANCED_LOAD_LEVELING"
