"""
Advanced WMS Enums.
"""
import enum

class StorageZoneType(str, enum.Enum):
    HIGH_BAY_RACK = "HIGH_BAY_RACK"
    MEZZANINE = "MEZZANINE"
    COLD_STORAGE_FREEZER = "COLD_STORAGE_FREEZER"
    HAZMAT_SECURED = "HAZMAT_SECURED"
    BULK_FLOOR_STACK = "BULK_FLOOR_STACK"
    FLOW_RACK_PICKING = "FLOW_RACK_PICKING"
    AUTOMATED_ASRS = "AUTOMATED_ASRS"

class PickingStrategy(str, enum.Enum):
    SINGLE_ORDER_PICK = "SINGLE_ORDER_PICK"
    WAVE_PICKING = "WAVE_PICKING"
    ZONE_PICKING = "ZONE_PICKING"
    CLUSTER_PICKING = "CLUSTER_PICKING"
    CROSS_DOCK_DIRECT = "CROSS_DOCK_DIRECT"

class PutawayRule(str, enum.Enum):
    VELOCITY_ABC_SLOT = "VELOCITY_ABC_SLOT"
    WEIGHT_HEAVY_BOTTOM = "WEIGHT_HEAVY_BOTTOM"
    CONSOLIDATE_EXISTING_LOT = "CONSOLIDATE_EXISTING_LOT"
    EMPTY_LOCATION_FIRST = "EMPTY_LOCATION_FIRST"

class DockDoorStatus(str, enum.Enum):
    AVAILABLE = "AVAILABLE"
    TRUCK_ARRIVED = "TRUCK_ARRIVED"
    UNLOADING = "UNLOADING"
    LOADING = "LOADING"
    MAINTENANCE = "MAINTENANCE"
