"""
IoT Predictive Maintenance Enums.
"""
import enum

class SensorType(str, enum.Enum):
    VIBRATION_TRI_AXIAL = "VIBRATION_TRI_AXIAL"
    THERMAL_INFRARED = "THERMAL_INFRARED"
    ACOUSTIC_ULTRASONIC = "ACOUSTIC_ULTRASONIC"
    CURRENT_AMPERAGE = "CURRENT_AMPERAGE"
    LUBRICATION_OIL_PARTICLE = "LUBRICATION_OIL_PARTICLE"

class MachineHealthCondition(str, enum.Enum):
    OPTIMAL_GREEN = "OPTIMAL_GREEN"
    WARNING_DEGRADATION_YELLOW = "WARNING_DEGRADATION_YELLOW"
    CRITICAL_FAILURE_IMMINENT_RED = "CRITICAL_FAILURE_IMMINENT_RED"
