"""
IoT Predictive Maintenance Database Models.
"""
from decimal import Decimal
from sqlalchemy import Column, String, Text, Numeric, Boolean, Date, DateTime, Integer, ForeignKey, Index, JSON
from sqlalchemy.orm import relationship
from backend.src.core.database import Base

class MachineTelemetrySensor(Base):
    """IoT sensor installed on critical shop-floor rotating equipment."""
    __tablename__ = "iot_sensors"

    sensor_id_code = Column(String(50), nullable=False, unique=True, index=True)
    machine_asset_id = Column(String(36), nullable=False, index=True)
    sensor_type = Column(String(40), default="VIBRATION_TRI_AXIAL", nullable=False)
    sampling_frequency_hz = Column(Integer, default=1000, nullable=False)
    is_online = Column(Boolean, default=True, nullable=False)
    current_health_score = Column(Integer, default=95, nullable=False)  # 0 - 100
    estimated_remaining_useful_life_hours = Column(Integer, default=4500, nullable=False)


class SensorAnomalyAlert(Base):
    """Real-time failure warning trigger generated by FFT spectrum analysis."""
    __tablename__ = "iot_sensor_alerts"

    sensor_id = Column(String(36), ForeignKey("iot_sensors.id"), nullable=False)
    timestamp = Column(DateTime(timezone=True), nullable=False)
    peak_vibration_mm_s = Column(Numeric(6, 2), nullable=False)
    bearing_fault_frequency = Column(String(50), nullable=True)  # BPFO, BPFI, BSF, FTF
    severity = Column(String(30), default="WARNING_DEGRADATION_YELLOW", nullable=False)
    automated_work_order_id = Column(String(36), nullable=True)
