"""
NexERP Financials Module Enums.
"""

from enum import Enum


class AccountType(str, Enum):
    ASSET = "ASSET"
    LIABILITY = "LIABILITY"
    EQUITY = "EQUITY"
    REVENUE = "REVENUE"
    EXPENSE = "EXPENSE"


class AccountClassification(str, Enum):
    # Assets
    CASH_AND_BANK = "CASH_AND_BANK"
    ACCOUNTS_RECEIVABLE = "ACCOUNTS_RECEIVABLE"
    INVENTORY = "INVENTORY"
    OTHER_CURRENT_ASSET = "OTHER_CURRENT_ASSET"
    PROPERTY_PLANT_EQUIPMENT = "PROPERTY_PLANT_EQUIPMENT"
    ACCUMULATED_DEPRECIATION = "ACCUMULATED_DEPRECIATION"
    INTANGIBLE_ASSET = "INTANGIBLE_ASSET"

    # Liabilities
    ACCOUNTS_PAYABLE = "ACCOUNTS_PAYABLE"
    TAX_PAYABLE = "TAX_PAYABLE"
    PAYROLL_PAYABLE = "PAYROLL_PAYABLE"
    SHORT_TERM_DEBT = "SHORT_TERM_DEBT"
    LONG_TERM_DEBT = "LONG_TERM_DEBT"

    # Equity
    RETAINED_EARNINGS = "RETAINED_EARNINGS"
    SHARE_CAPITAL = "SHARE_CAPITAL"
    DIVIDENDS_PAID = "DIVIDENDS_PAID"

    # Revenue
    OPERATING_REVENUE = "OPERATING_REVENUE"
    SALES_DISCOUNTS = "SALES_DISCOUNTS"
    OTHER_INCOME = "OTHER_INCOME"
    FINANCIAL_INCOME = "FINANCIAL_INCOME"

    # Expense
    COST_OF_GOODS_SOLD = "COST_OF_GOODS_SOLD"
    SALARIES_AND_WAGES = "SALARIES_AND_WAGES"
    DEPRECIATION_EXPENSE = "DEPRECIATION_EXPENSE"
    RENT_AND_UTILITIES = "RENT_AND_UTILITIES"
    MARKETING_EXPENSE = "MARKETING_EXPENSE"
    GENERAL_AND_ADMIN = "GENERAL_AND_ADMIN"
    TAX_EXPENSE = "TAX_EXPENSE"
    FX_GAIN_LOSS = "FX_GAIN_LOSS"


class JournalStatus(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    POSTED = "POSTED"
    REVERSED = "REVERSED"


class DepreciationMethod(str, Enum):
    STRAIGHT_LINE = "STRAIGHT_LINE"
    DOUBLE_DECLINING = "DOUBLE_DECLINING"
    DOUBLE_DECLINING_BALANCE = "DOUBLE_DECLINING_BALANCE"
    SUM_OF_YEARS_DIGITS = "SUM_OF_YEARS_DIGITS"
    MACRS = "MACRS"


class AssetStatus(str, Enum):
    ACTIVE = "ACTIVE"
    FULLY_DEPRECIATED = "FULLY_DEPRECIATED"
    DISPOSED = "DISPOSED"
