"""
Tax Engine Enums.
"""
import enum

class TaxType(str, enum.Enum):
    US_SALES_USE_TAX = "US_SALES_USE_TAX"
    EU_VAT_STANDARD = "EU_VAT_STANDARD"
    EU_VAT_REDUCED = "EU_VAT_REDUCED"
    EU_VAT_REVERSE_CHARGE = "EU_VAT_REVERSE_CHARGE"
    WITHHOLDING_TAX_DIVIDEND = "WITHHOLDING_TAX_DIVIDEND"
    WITHHOLDING_TAX_ROYALTY = "WITHHOLDING_TAX_ROYALTY"
    CANADIAN_GST_HST = "CANADIAN_GST_HST"
    INDIAN_GST = "INDIAN_GST"

class NexusType(str, enum.Enum):
    PHYSICAL_PRESENCE = "PHYSICAL_PRESENCE"
    ECONOMIC_THRESHOLD_WAYFAIR = "ECONOMIC_THRESHOLD_WAYFAIR"
    CLICK_THROUGH_AFFILIATE = "CLICK_THROUGH_AFFILIATE"
    WAREHOUSE_FBA_FULFILLMENT = "WAREHOUSE_FBA_FULFILLMENT"
