"""
Customer Self-Service Portal Enums.
"""
import enum

class SupportTicketSeverity(str, enum.Enum):
    SEV_1_CRITICAL_OUTAGE = "SEV_1_CRITICAL_OUTAGE"
    SEV_2_HIGH_DEGRADATION = "SEV_2_HIGH_DEGRADATION"
    SEV_3_MEDIUM_INQUIRY = "SEV_3_MEDIUM_INQUIRY"
    SEV_4_LOW_FEATURE_REQ = "SEV_4_LOW_FEATURE_REQ"

class RMAReturnStatus(str, enum.Enum):
    REQUESTED = "REQUESTED"
    AUTHORIZED_LABEL_ISSUED = "AUTHORIZED_LABEL_ISSUED"
    PACKAGE_RECEIVED_INSPECTION = "PACKAGE_RECEIVED_INSPECTION"
    CREDIT_MEMO_ISSUED = "CREDIT_MEMO_ISSUED"
    REJECTED_DAMAGED = "REJECTED_DAMAGED"
