"""
Strategic Budgeting Enums.
"""
import enum

class BudgetVersionType(str, enum.Enum):
    ORIGINAL_APPROVED = "ORIGINAL_APPROVED"
    MID_YEAR_REVISED = "MID_YEAR_REVISED"
    ROLLING_FORECAST_18M = "ROLLING_FORECAST_18M"
    WORST_CASE_DOWNTURN = "WORST_CASE_DOWNTURN"
    OPTIMISTIC_EXPANSION = "OPTIMISTIC_EXPANSION"

class BudgetStatus(str, enum.Enum):
    DRAFT_PREPARATION = "DRAFT_PREPARATION"
    UNDER_CFO_REVIEW = "UNDER_CFO_REVIEW"
    BOARD_APPROVED = "BOARD_APPROVED"
    LOCKED_FROZEN = "LOCKED_FROZEN"
    ARCHIVED = "ARCHIVED"

class CostCenterExpenseType(str, enum.Enum):
    OPEX_HEADCOUNT = "OPEX_HEADCOUNT"
    OPEX_MARKETING = "OPEX_MARKETING"
    OPEX_INFRASTRUCTURE = "OPEX_INFRASTRUCTURE"
    OPEX_TRAVEL_ENTERTAINMENT = "OPEX_TRAVEL_ENTERTAINMENT"
    CAPEX_EQUIPMENT = "CAPEX_EQUIPMENT"
    COGS_DIRECT_LABOR = "COGS_DIRECT_LABOR"
