"""
US GAAP & IFRS Standard Enterprise Chart of Accounts (COA) Master Taxonomy.
Hierarchical account codes, classifications, normal balance directions, and XBRL US GAAP 2026 tags.
"""

GAAP_CHART_OF_ACCOUNTS_TAXONOMY = [
    {
        "account_code": "10100",
        "account_name": "Operating Cash & Checking Account",
        "account_type": "ASSET",
        "classification": "Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "CashAndCashEquivalentsAtCarryingValue",
        "is_reconcilable": True,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "10110",
        "account_name": "Payroll Clearing Account",
        "account_type": "ASSET",
        "classification": "Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "CashAndCashEquivalentsAtCarryingValue",
        "is_reconcilable": True,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "10120",
        "account_name": "Petty Cash Imprest Fund",
        "account_type": "ASSET",
        "classification": "Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "CashAndCashEquivalentsAtCarryingValue",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "10200",
        "account_name": "Short-Term Treasury Bills & Money Market",
        "account_type": "ASSET",
        "classification": "Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "MarketableSecuritiesCurrent",
        "is_reconcilable": True,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "10300",
        "account_name": "Trade Accounts Receivable (Billed)",
        "account_type": "ASSET",
        "classification": "Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "AccountsReceivableNetCurrent",
        "is_reconcilable": True,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "10310",
        "account_name": "Unbilled Receivables (Contract WIP)",
        "account_type": "ASSET",
        "classification": "Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "UnbilledReceivablesCurrent",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "10390",
        "account_name": "Allowance for Expected Credit Losses (CECL)",
        "account_type": "ASSET",
        "classification": "Current Asset",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "AllowanceForDoubtfulAccountsReceivableCurrent",
        "is_reconcilable": True,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "10400",
        "account_name": "Inventory - Raw Materials & Components",
        "account_type": "ASSET",
        "classification": "Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "InventoryRawMaterials",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "10410",
        "account_name": "Inventory - Work In Process (WIP)",
        "account_type": "ASSET",
        "classification": "Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "InventoryWorkInProcess",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "10420",
        "account_name": "Inventory - Finished Goods Warehoused",
        "account_type": "ASSET",
        "classification": "Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "InventoryFinishedGoods",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "10430",
        "account_name": "Inventory - Goods In Transit (FOB Shipping)",
        "account_type": "ASSET",
        "classification": "Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "InventoryInTransit",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "10490",
        "account_name": "Inventory SLOB Obsolescence Reserve",
        "account_type": "ASSET",
        "classification": "Current Asset",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "InventoryValuationReserves",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "10500",
        "account_name": "Prepaid Commercial Property Insurance",
        "account_type": "ASSET",
        "classification": "Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "PrepaidInsurance",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "10510",
        "account_name": "Prepaid Facility Lease & Rent",
        "account_type": "ASSET",
        "classification": "Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "PrepaidRent",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "10520",
        "account_name": "Prepaid Software SaaS Subscriptions",
        "account_type": "ASSET",
        "classification": "Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "PrepaidExpenseCurrent",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "10600",
        "account_name": "Income Tax Refundable & Advance Tax",
        "account_type": "ASSET",
        "classification": "Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "IncomeTaxesReceivable",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "15100",
        "account_name": "Commercial Land & Building Improvements",
        "account_type": "ASSET",
        "classification": "Non-Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "LandAndBuildingImprovements",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "15200",
        "account_name": "CNC Machinery & Robotic Manufacturing Equipment",
        "account_type": "ASSET",
        "classification": "Non-Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "MachineryAndEquipmentGross",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "15290",
        "account_name": "Accumulated Depreciation - Machinery",
        "account_type": "ASSET",
        "classification": "Non-Current Asset",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "15300",
        "account_name": "Fleet Transport Trucks & Delivery Vans",
        "account_type": "ASSET",
        "classification": "Non-Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "VehiclesGross",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "15390",
        "account_name": "Accumulated Depreciation - Vehicles",
        "account_type": "ASSET",
        "classification": "Non-Current Asset",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "AccumulatedDepreciationVehicles",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "15400",
        "account_name": "Computer Servers & Network Infrastructure",
        "account_type": "ASSET",
        "classification": "Non-Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "ComputerEquipmentGross",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "15490",
        "account_name": "Accumulated Depreciation - IT Equipment",
        "account_type": "ASSET",
        "classification": "Non-Current Asset",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "AccumulatedDepreciationComputerEquipment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "16100",
        "account_name": "Capitalized Software Development (ASC 350-40)",
        "account_type": "ASSET",
        "classification": "Non-Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "CapitalizedSoftwareDevelopmentCosts",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "16190",
        "account_name": "Accumulated Amortization - Software",
        "account_type": "ASSET",
        "classification": "Non-Current Asset",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "AccumulatedAmortizationSoftware",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "16200",
        "account_name": "Patents, Trademarks & Intellectual Property",
        "account_type": "ASSET",
        "classification": "Non-Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "PatentsAndTrademarksGross",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "17100",
        "account_name": "Operating Lease Right-of-Use Asset (ASC 842)",
        "account_type": "ASSET",
        "classification": "Non-Current Asset",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingLeaseRightOfUseAsset",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "17190",
        "account_name": "Accumulated Amortization - ROU Assets",
        "account_type": "ASSET",
        "classification": "Non-Current Asset",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "OperatingLeaseRightOfUseAssetAmortization",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "20100",
        "account_name": "Trade Accounts Payable (Vendors)",
        "account_type": "LIABILITY",
        "classification": "Current Liability",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "AccountsPayableCurrent",
        "is_reconcilable": True,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "20110",
        "account_name": "Accrued Incurred But Not Received (GRNI)",
        "account_type": "LIABILITY",
        "classification": "Current Liability",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "AccruedLiabilitiesCurrent",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "20200",
        "account_name": "Accrued Gross Payroll & Wages",
        "account_type": "LIABILITY",
        "classification": "Current Liability",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "EmployeeRelatedLiabilitiesCurrent",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "20210",
        "account_name": "Accrued Paid Time Off (PTO) & Leave",
        "account_type": "LIABILITY",
        "classification": "Current Liability",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "CompensatedAbsencesCurrent",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "20220",
        "account_name": "Federal & State Payroll Taxes Payable",
        "account_type": "LIABILITY",
        "classification": "Current Liability",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "TaxesPayableCurrent",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "20300",
        "account_name": "Sales & Use Tax Collected Payable",
        "account_type": "LIABILITY",
        "classification": "Current Liability",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "SalesTaxPayableCurrent",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "20400",
        "account_name": "Short-Term Unearned Deferred Revenue (ASC 606)",
        "account_type": "LIABILITY",
        "classification": "Current Liability",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "ContractWithCustomerLiabilityCurrent",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "20500",
        "account_name": "Current Portion of Long-Term Term Debt",
        "account_type": "LIABILITY",
        "classification": "Current Liability",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "LongTermDebtCurrent",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "20600",
        "account_name": "Operating Lease Liability - Current (ASC 842)",
        "account_type": "LIABILITY",
        "classification": "Current Liability",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "OperatingLeaseLiabilityCurrent",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "25100",
        "account_name": "Senior Secured Term Loan Facility (2028)",
        "account_type": "LIABILITY",
        "classification": "Non-Current Liability",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "LongTermDebtNoncurrent",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "25200",
        "account_name": "Operating Lease Liability - Non-Current (ASC 842)",
        "account_type": "LIABILITY",
        "classification": "Non-Current Liability",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "OperatingLeaseLiabilityNoncurrent",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "25300",
        "account_name": "Deferred Income Tax Liability (ASC 740)",
        "account_type": "LIABILITY",
        "classification": "Non-Current Liability",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "DeferredIncomeTaxLiabilitiesNet",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "30100",
        "account_name": "Common Stock ($0.01 par, 50,000,000 authorized)",
        "account_type": "EQUITY",
        "classification": "Stockholders Equity",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "CommonStockValue",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "30200",
        "account_name": "Additional Paid-In Capital (APIC)",
        "account_type": "EQUITY",
        "classification": "Stockholders Equity",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "AdditionalPaidInCapital",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "30300",
        "account_name": "Retained Earnings (Accumulated Deficit)",
        "account_type": "EQUITY",
        "classification": "Stockholders Equity",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "RetainedEarningsAccumulatedDeficit",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "30400",
        "account_name": "Accumulated Other Comprehensive Income (AOCI)",
        "account_type": "EQUITY",
        "classification": "Stockholders Equity",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "AccumulatedOtherComprehensiveIncomeLossNetOfTax",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "40100",
        "account_name": "Enterprise SaaS Software Subscriptions",
        "account_type": "REVENUE",
        "classification": "Operating Revenue",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "SubscriptionRevenue",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "40200",
        "account_name": "Professional Implementation & Customization Services",
        "account_type": "REVENUE",
        "classification": "Operating Revenue",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "ProfessionalServicesRevenue",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "40300",
        "account_name": "Managed SLA Maintenance & Technical Support",
        "account_type": "REVENUE",
        "classification": "Operating Revenue",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "MaintenanceRevenue",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "40400",
        "account_name": "Hardware Appliance & IoT Gateway Sales",
        "account_type": "REVENUE",
        "classification": "Operating Revenue",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "HardwareRevenue",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "40900",
        "account_name": "Customer Volume Rebates & Sales Discounts",
        "account_type": "REVENUE",
        "classification": "Operating Revenue",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "SalesDiscountsAndAllowances",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50100",
        "account_name": "COGS - Cloud Hosting Datacenter Compute",
        "account_type": "EXPENSE",
        "classification": "Cost of Goods Sold",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "HostingCostOfGoodsSold",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50200",
        "account_name": "COGS - Customer Support Direct Salaries",
        "account_type": "EXPENSE",
        "classification": "Cost of Goods Sold",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "DirectLaborCostOfGoodsSold",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50300",
        "account_name": "COGS - Third-Party Embedded Software Royalties",
        "account_type": "EXPENSE",
        "classification": "Cost of Goods Sold",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "RoyaltiesCostOfGoodsSold",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50400",
        "account_name": "COGS - Direct Manufacturing Materials Consumed",
        "account_type": "EXPENSE",
        "classification": "Cost of Goods Sold",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "CostOfGoodsSoldRawMaterials",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50500",
        "account_name": "COGS - Manufacturing Direct Shopfloor Labor",
        "account_type": "EXPENSE",
        "classification": "Cost of Goods Sold",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "CostOfGoodsSoldDirectLabor",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50600",
        "account_name": "COGS - Applied Machine Overhead & Depreciation",
        "account_type": "EXPENSE",
        "classification": "Cost of Goods Sold",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "CostOfGoodsSoldOverhead",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60100",
        "account_name": "R&D - Software Engineering Salaries & Wages",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "ResearchAndDevelopmentExpenseSalaries",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60110",
        "account_name": "R&D - Stock-Based Equity Compensation (ASC 718)",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "ShareBasedCompensationExpense",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60120",
        "account_name": "R&D - Cloud Testing & Sandbox Environments",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "ResearchAndDevelopmentExpenseOther",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60200",
        "account_name": "S&M - Sales Quota Commission Expense",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "SalesCommissionsExpense",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60210",
        "account_name": "S&M - Digital Advertising & Campaign Spend",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "MarketingAndAdvertisingExpense",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60220",
        "account_name": "S&M - Field Travel & Customer Entertainment",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "TravelAndEntertainmentExpense",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60300",
        "account_name": "G&A - Executive & Corporate Administrative Salaries",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "GeneralAndAdministrativeExpenseSalaries",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60310",
        "account_name": "G&A - Legal Counsel & Audit Advisory Fees",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "LegalAndProfessionalFees",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60320",
        "account_name": "G&A - Director & Officer (D&O) Insurance",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "InsuranceExpense",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60330",
        "account_name": "G&A - Corporate Facilities Office Rent",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "LeaseAndRentalExpense",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60400",
        "account_name": "G&A - Bad Debt Provision Expense (CECL)",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "ProvisionForDoubtfulAccounts",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "70100",
        "account_name": "Interest Income on Cash & Short-Term Deposits",
        "account_type": "REVENUE",
        "classification": "Non-Operating Item",
        "normal_balance": "CREDIT",
        "xbrl_us_gaap_tag": "InvestmentIncomeNet",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "70200",
        "account_name": "Interest Expense on Senior Term Loan",
        "account_type": "EXPENSE",
        "classification": "Non-Operating Item",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "InterestExpenseDebt",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "70300",
        "account_name": "Realized & Unrealized Foreign Currency Gain/Loss",
        "account_type": "EXPENSE",
        "classification": "Non-Operating Item",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "ForeignCurrencyTransactionGainLossBeforeTax",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "80100",
        "account_name": "Provision for Federal & State Income Taxes",
        "account_type": "EXPENSE",
        "classification": "Income Tax Provision",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "IncomeTaxExpenseBenefit",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60100-100",
        "account_name": "Corporate HQ - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60200-100",
        "account_name": "Corporate HQ - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60300-100",
        "account_name": "Corporate HQ - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60330-100",
        "account_name": "Corporate HQ - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50400-100",
        "account_name": "Corporate HQ - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50500-100",
        "account_name": "Corporate HQ - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60100-200",
        "account_name": "R&D Engineering - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60200-200",
        "account_name": "R&D Engineering - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60300-200",
        "account_name": "R&D Engineering - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60330-200",
        "account_name": "R&D Engineering - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50400-200",
        "account_name": "R&D Engineering - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50500-200",
        "account_name": "R&D Engineering - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60100-300",
        "account_name": "Sales North America - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60200-300",
        "account_name": "Sales North America - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60300-300",
        "account_name": "Sales North America - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60330-300",
        "account_name": "Sales North America - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50400-300",
        "account_name": "Sales North America - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50500-300",
        "account_name": "Sales North America - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60100-310",
        "account_name": "Sales EMEA - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60200-310",
        "account_name": "Sales EMEA - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60300-310",
        "account_name": "Sales EMEA - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60330-310",
        "account_name": "Sales EMEA - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50400-310",
        "account_name": "Sales EMEA - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50500-310",
        "account_name": "Sales EMEA - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60100-320",
        "account_name": "Sales APAC - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60200-320",
        "account_name": "Sales APAC - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60300-320",
        "account_name": "Sales APAC - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60330-320",
        "account_name": "Sales APAC - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50400-320",
        "account_name": "Sales APAC - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50500-320",
        "account_name": "Sales APAC - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60100-400",
        "account_name": "Customer Success - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60200-400",
        "account_name": "Customer Success - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60300-400",
        "account_name": "Customer Success - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60330-400",
        "account_name": "Customer Success - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50400-400",
        "account_name": "Customer Success - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50500-400",
        "account_name": "Customer Success - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60100-500",
        "account_name": "Manufacturing Austin - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60200-500",
        "account_name": "Manufacturing Austin - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60300-500",
        "account_name": "Manufacturing Austin - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60330-500",
        "account_name": "Manufacturing Austin - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50400-500",
        "account_name": "Manufacturing Austin - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50500-500",
        "account_name": "Manufacturing Austin - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60100-510",
        "account_name": "Manufacturing Dallas - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60200-510",
        "account_name": "Manufacturing Dallas - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60300-510",
        "account_name": "Manufacturing Dallas - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60330-510",
        "account_name": "Manufacturing Dallas - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50400-510",
        "account_name": "Manufacturing Dallas - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50500-510",
        "account_name": "Manufacturing Dallas - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60100-600",
        "account_name": "Supply Chain DC - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60200-600",
        "account_name": "Supply Chain DC - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60300-600",
        "account_name": "Supply Chain DC - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "60330-600",
        "account_name": "Supply Chain DC - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50400-600",
        "account_name": "Supply Chain DC - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
    {
        "account_code": "50500-600",
        "account_name": "Supply Chain DC - Sub Expense Account",
        "account_type": "EXPENSE",
        "classification": "Operating Expense",
        "normal_balance": "DEBIT",
        "xbrl_us_gaap_tag": "OperatingExpensesBySegment",
        "is_reconcilable": False,
        "currency": "USD",
        "is_header_only": False,
    },
]
