"""
US GAAP & IFRS Statutory Financial Disclosure Footnote Templates.
Standard footnote templates for revenue recognition, leases, stock compensation, and debt maturities.
"""

GAAP_IFRS_DISCLOSURE_TEMPLATES = [
    {
        "disclosure_code": "DISC-REV-ASC606-000",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 1)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-001",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 2)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-002",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 3)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-003",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 4)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-004",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 5)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-005",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 6)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-006",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 7)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-007",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 8)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-008",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 9)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-009",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 10)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-010",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 11)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-011",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 12)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-012",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 13)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-013",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 14)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-014",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 15)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-015",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 16)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-016",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 17)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-017",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 18)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-018",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 19)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-019",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 20)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-020",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 21)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-021",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 22)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-022",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 23)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-023",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 24)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-024",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 25)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-025",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 26)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-026",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 27)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-027",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 28)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-028",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 29)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-029",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 30)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-030",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 31)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-031",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 32)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-032",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 33)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-033",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 34)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-034",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 35)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-035",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 36)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-036",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 37)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-037",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 38)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-038",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 39)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-039",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 40)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-040",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 41)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-041",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 42)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-042",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 43)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-043",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 44)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-044",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 45)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-045",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 46)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-046",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 47)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-047",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 48)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-048",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 49)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-049",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 50)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-050",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 51)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-051",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 52)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-052",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 53)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-053",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 54)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-054",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 55)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-055",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 56)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-056",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 57)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-057",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 58)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-058",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 59)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-059",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 60)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-060",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 61)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-061",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 62)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-062",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 63)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-063",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 64)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-064",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 65)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-065",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 66)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-066",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 67)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-067",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 68)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-068",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 69)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-069",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 70)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-070",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 71)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-071",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 72)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-072",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 73)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-073",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 74)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-074",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 75)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-075",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 76)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-076",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 77)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-077",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 78)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-078",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 79)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-079",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 80)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-080",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 81)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-081",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 82)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-082",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 83)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-083",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 84)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-084",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 85)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-085",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 86)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-086",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 87)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-087",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 88)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-088",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 89)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-089",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 90)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-090",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 91)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-091",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 92)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-092",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 93)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-093",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 94)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-094",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 95)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-095",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 96)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-096",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 97)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-097",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 98)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-098",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 99)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-099",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 100)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-100",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 101)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-101",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 102)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-102",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 103)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-103",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 104)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-104",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 105)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-105",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 106)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-106",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 107)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-107",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 108)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-108",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 109)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-109",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 110)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-110",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 111)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-111",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 112)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-112",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 113)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-113",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 114)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-114",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 115)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-115",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 116)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-116",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 117)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-117",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 118)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-118",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 119)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-119",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 120)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-120",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 121)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-121",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 122)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-122",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 123)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-123",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 124)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-124",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 125)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-125",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 126)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-126",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 127)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-127",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 128)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-128",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 129)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-129",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 130)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-130",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 131)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-131",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 132)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-132",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 133)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-133",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 134)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-134",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 135)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-135",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 136)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-136",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 137)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-137",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 138)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-138",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 139)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-139",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 140)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-140",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 141)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-141",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 142)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-142",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 143)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-143",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 144)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-144",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 145)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-145",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 146)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-146",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 147)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-147",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 148)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-148",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 149)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-149",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 150)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-150",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 151)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-151",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 152)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-REV-ASC606-152",
        "footnote_title": "Note 2: Disaggregation of Revenue from Contracts with Customers (Exhibit 153)",
        "accounting_topic": "REVENUE_ASC606",
        "disclosure_summary": "Disaggregates revenue by product line, timing of transfer, and geographic customer region.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-LSE-ASC842-153",
        "footnote_title": "Note 8: Operating and Finance Lease Right-of-Use Assets & Maturity Schedule (Exhibit 154)",
        "accounting_topic": "LEASES_ASC842",
        "disclosure_summary": "Undiscounted contractual cash flow maturity schedule for next 5 years and thereafter with IBR reconciliation.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-STK-ASC718-154",
        "footnote_title": "Note 14: Stock-Based Compensation & Equity Incentive Plan (Exhibit 155)",
        "accounting_topic": "STOCK_COMPENSATION_ASC718",
        "disclosure_summary": "Black-Scholes valuation assumptions, weighted-average strike price, expected volatility, and unamortized expense.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-DEB-ASC470-155",
        "footnote_title": "Note 9: Long-Term Debt, Credit Facilities, and Financial Covenants (Exhibit 156)",
        "accounting_topic": "DEBT_ASC470",
        "disclosure_summary": "Principal maturities, interest rate spreads, leverage ratio covenant thresholds, and collateral pledges.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-TAX-ASC740-156",
        "footnote_title": "Note 12: Income Taxes, Deferred Tax Assets, and Valuation Allowance (Exhibit 157)",
        "accounting_topic": "TAX_ASC740",
        "disclosure_summary": "Effective tax rate reconciliation, net operating loss (NOL) carryforward expiration schedules, and valuation allowances.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-FAV-ASC820-157",
        "footnote_title": "Note 15: Fair Value Measurements Hierarchy (Level 1, Level 2, Level 3) (Exhibit 158)",
        "accounting_topic": "FAIR_VALUE_ASC820",
        "disclosure_summary": "Classification of financial instruments, FX derivative hedges, and marketable securities across fair value levels.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-SEG-ASC280-158",
        "footnote_title": "Note 18: Segment Reporting and Geographic Information (Exhibit 159)",
        "accounting_topic": "SEGMENTS_ASC280",
        "disclosure_summary": "Operating segment revenues, adjusted EBITDA, long-lived assets by geographic country boundary.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
    {
        "disclosure_code": "DISC-CON-ASC450-159",
        "footnote_title": "Note 16: Commitments and Contingencies (Legal and Environmental) (Exhibit 160)",
        "accounting_topic": "CONTINGENCIES_ASC450",
        "disclosure_summary": "Assessment of probable, reasonably possible, and remote loss contingencies and indemnification obligations.",
        "mandatory_filing": True,
        "applicable_standards": ["US_GAAP", "IFRS"],
    },
]
