"""
EPA & IPCC GHG Protocol Greenhouse Gas Emission Factors Master Library.
Standard emission conversion factors for Scope 1, Scope 2, and Scope 3 activity categories.
"""

GHG_PROTOCOL_EMISSION_FACTORS_LIBRARY = [
    {
        "factor_id": "GHG-SC1-001-000",
        "emission_source_name": "Natural Gas Combustion (Industrial Boiler) (Series 1)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "MMBtu",
        "emission_factor_kg_co2e_per_unit": 53.06,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-002-001",
        "emission_source_name": "Diesel Fuel Combustion (Stationary Generator) (Series 2)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 10.21,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-003-002",
        "emission_source_name": "Motor Gasoline (Corporate Fleet Vehicles) (Series 3)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 8.78,
        "reference_standard_source": "EPA Climate Leaders",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-004-003",
        "emission_source_name": "Propane / LPG (Forklift & Warehouse Heating) (Series 4)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 5.72,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-005-004",
        "emission_source_name": "Refrigerant Fugitive Losses (R-410A HFC) (Series 5)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 2088.0,
        "reference_standard_source": "IPCC Fifth Assessment AR5",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-001-005",
        "emission_source_name": "Grid Electricity - US ERCOT Texas Region (Series 6)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 380.2,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-002-006",
        "emission_source_name": "Grid Electricity - US WECC California Region (Series 7)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 210.4,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-003-007",
        "emission_source_name": "Grid Electricity - US RFC East Mid-Atlantic (Series 8)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 325.8,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-004-008",
        "emission_source_name": "Grid Electricity - UK National Grid Average (Series 9)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 198.5,
        "reference_standard_source": "UK DEFRA GHG Guidelines",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-005-009",
        "emission_source_name": "Grid Electricity - Germany Federal Grid Mix (Series 10)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 345.0,
        "reference_standard_source": "UBA German Environment Agency",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-001-010",
        "emission_source_name": "Air Freight Cargo - Long Haul International (Series 11)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.602,
        "reference_standard_source": "ICAO Carbon Calculator",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-002-011",
        "emission_source_name": "Ocean Freight - Container Vessel FCL (Series 12)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.016,
        "reference_standard_source": "Clean Cargo Working Group",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-003-012",
        "emission_source_name": "Road Freight Truckload - Class 8 Heavy Truck (Series 13)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.105,
        "reference_standard_source": "SmartWay EPA Logistics",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-004-013",
        "emission_source_name": "Data Center Cloud Compute Server Hour (PUE 1.2) (Series 14)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Instance-hr",
        "emission_factor_kg_co2e_per_unit": 0.015,
        "reference_standard_source": "Cloud Carbon Footprint Methodology",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-005-014",
        "emission_source_name": "Virgin Aluminum Ingot Smelting Activity (Series 15)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 8.24,
        "reference_standard_source": "International Aluminium Institute",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-001-015",
        "emission_source_name": "Natural Gas Combustion (Industrial Boiler) (Series 16)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "MMBtu",
        "emission_factor_kg_co2e_per_unit": 53.06,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-002-016",
        "emission_source_name": "Diesel Fuel Combustion (Stationary Generator) (Series 17)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 10.21,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-003-017",
        "emission_source_name": "Motor Gasoline (Corporate Fleet Vehicles) (Series 18)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 8.78,
        "reference_standard_source": "EPA Climate Leaders",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-004-018",
        "emission_source_name": "Propane / LPG (Forklift & Warehouse Heating) (Series 19)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 5.72,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-005-019",
        "emission_source_name": "Refrigerant Fugitive Losses (R-410A HFC) (Series 20)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 2088.0,
        "reference_standard_source": "IPCC Fifth Assessment AR5",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-001-020",
        "emission_source_name": "Grid Electricity - US ERCOT Texas Region (Series 21)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 380.2,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-002-021",
        "emission_source_name": "Grid Electricity - US WECC California Region (Series 22)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 210.4,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-003-022",
        "emission_source_name": "Grid Electricity - US RFC East Mid-Atlantic (Series 23)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 325.8,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-004-023",
        "emission_source_name": "Grid Electricity - UK National Grid Average (Series 24)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 198.5,
        "reference_standard_source": "UK DEFRA GHG Guidelines",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-005-024",
        "emission_source_name": "Grid Electricity - Germany Federal Grid Mix (Series 25)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 345.0,
        "reference_standard_source": "UBA German Environment Agency",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-001-025",
        "emission_source_name": "Air Freight Cargo - Long Haul International (Series 26)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.602,
        "reference_standard_source": "ICAO Carbon Calculator",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-002-026",
        "emission_source_name": "Ocean Freight - Container Vessel FCL (Series 27)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.016,
        "reference_standard_source": "Clean Cargo Working Group",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-003-027",
        "emission_source_name": "Road Freight Truckload - Class 8 Heavy Truck (Series 28)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.105,
        "reference_standard_source": "SmartWay EPA Logistics",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-004-028",
        "emission_source_name": "Data Center Cloud Compute Server Hour (PUE 1.2) (Series 29)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Instance-hr",
        "emission_factor_kg_co2e_per_unit": 0.015,
        "reference_standard_source": "Cloud Carbon Footprint Methodology",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-005-029",
        "emission_source_name": "Virgin Aluminum Ingot Smelting Activity (Series 30)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 8.24,
        "reference_standard_source": "International Aluminium Institute",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-001-030",
        "emission_source_name": "Natural Gas Combustion (Industrial Boiler) (Series 31)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "MMBtu",
        "emission_factor_kg_co2e_per_unit": 53.06,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-002-031",
        "emission_source_name": "Diesel Fuel Combustion (Stationary Generator) (Series 32)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 10.21,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-003-032",
        "emission_source_name": "Motor Gasoline (Corporate Fleet Vehicles) (Series 33)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 8.78,
        "reference_standard_source": "EPA Climate Leaders",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-004-033",
        "emission_source_name": "Propane / LPG (Forklift & Warehouse Heating) (Series 34)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 5.72,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-005-034",
        "emission_source_name": "Refrigerant Fugitive Losses (R-410A HFC) (Series 35)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 2088.0,
        "reference_standard_source": "IPCC Fifth Assessment AR5",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-001-035",
        "emission_source_name": "Grid Electricity - US ERCOT Texas Region (Series 36)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 380.2,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-002-036",
        "emission_source_name": "Grid Electricity - US WECC California Region (Series 37)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 210.4,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-003-037",
        "emission_source_name": "Grid Electricity - US RFC East Mid-Atlantic (Series 38)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 325.8,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-004-038",
        "emission_source_name": "Grid Electricity - UK National Grid Average (Series 39)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 198.5,
        "reference_standard_source": "UK DEFRA GHG Guidelines",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-005-039",
        "emission_source_name": "Grid Electricity - Germany Federal Grid Mix (Series 40)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 345.0,
        "reference_standard_source": "UBA German Environment Agency",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-001-040",
        "emission_source_name": "Air Freight Cargo - Long Haul International (Series 41)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.602,
        "reference_standard_source": "ICAO Carbon Calculator",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-002-041",
        "emission_source_name": "Ocean Freight - Container Vessel FCL (Series 42)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.016,
        "reference_standard_source": "Clean Cargo Working Group",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-003-042",
        "emission_source_name": "Road Freight Truckload - Class 8 Heavy Truck (Series 43)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.105,
        "reference_standard_source": "SmartWay EPA Logistics",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-004-043",
        "emission_source_name": "Data Center Cloud Compute Server Hour (PUE 1.2) (Series 44)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Instance-hr",
        "emission_factor_kg_co2e_per_unit": 0.015,
        "reference_standard_source": "Cloud Carbon Footprint Methodology",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-005-044",
        "emission_source_name": "Virgin Aluminum Ingot Smelting Activity (Series 45)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 8.24,
        "reference_standard_source": "International Aluminium Institute",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-001-045",
        "emission_source_name": "Natural Gas Combustion (Industrial Boiler) (Series 46)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "MMBtu",
        "emission_factor_kg_co2e_per_unit": 53.06,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-002-046",
        "emission_source_name": "Diesel Fuel Combustion (Stationary Generator) (Series 47)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 10.21,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-003-047",
        "emission_source_name": "Motor Gasoline (Corporate Fleet Vehicles) (Series 48)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 8.78,
        "reference_standard_source": "EPA Climate Leaders",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-004-048",
        "emission_source_name": "Propane / LPG (Forklift & Warehouse Heating) (Series 49)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 5.72,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-005-049",
        "emission_source_name": "Refrigerant Fugitive Losses (R-410A HFC) (Series 50)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 2088.0,
        "reference_standard_source": "IPCC Fifth Assessment AR5",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-001-050",
        "emission_source_name": "Grid Electricity - US ERCOT Texas Region (Series 51)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 380.2,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-002-051",
        "emission_source_name": "Grid Electricity - US WECC California Region (Series 52)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 210.4,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-003-052",
        "emission_source_name": "Grid Electricity - US RFC East Mid-Atlantic (Series 53)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 325.8,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-004-053",
        "emission_source_name": "Grid Electricity - UK National Grid Average (Series 54)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 198.5,
        "reference_standard_source": "UK DEFRA GHG Guidelines",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-005-054",
        "emission_source_name": "Grid Electricity - Germany Federal Grid Mix (Series 55)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 345.0,
        "reference_standard_source": "UBA German Environment Agency",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-001-055",
        "emission_source_name": "Air Freight Cargo - Long Haul International (Series 56)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.602,
        "reference_standard_source": "ICAO Carbon Calculator",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-002-056",
        "emission_source_name": "Ocean Freight - Container Vessel FCL (Series 57)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.016,
        "reference_standard_source": "Clean Cargo Working Group",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-003-057",
        "emission_source_name": "Road Freight Truckload - Class 8 Heavy Truck (Series 58)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.105,
        "reference_standard_source": "SmartWay EPA Logistics",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-004-058",
        "emission_source_name": "Data Center Cloud Compute Server Hour (PUE 1.2) (Series 59)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Instance-hr",
        "emission_factor_kg_co2e_per_unit": 0.015,
        "reference_standard_source": "Cloud Carbon Footprint Methodology",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-005-059",
        "emission_source_name": "Virgin Aluminum Ingot Smelting Activity (Series 60)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 8.24,
        "reference_standard_source": "International Aluminium Institute",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-001-060",
        "emission_source_name": "Natural Gas Combustion (Industrial Boiler) (Series 61)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "MMBtu",
        "emission_factor_kg_co2e_per_unit": 53.06,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-002-061",
        "emission_source_name": "Diesel Fuel Combustion (Stationary Generator) (Series 62)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 10.21,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-003-062",
        "emission_source_name": "Motor Gasoline (Corporate Fleet Vehicles) (Series 63)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 8.78,
        "reference_standard_source": "EPA Climate Leaders",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-004-063",
        "emission_source_name": "Propane / LPG (Forklift & Warehouse Heating) (Series 64)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 5.72,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-005-064",
        "emission_source_name": "Refrigerant Fugitive Losses (R-410A HFC) (Series 65)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 2088.0,
        "reference_standard_source": "IPCC Fifth Assessment AR5",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-001-065",
        "emission_source_name": "Grid Electricity - US ERCOT Texas Region (Series 66)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 380.2,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-002-066",
        "emission_source_name": "Grid Electricity - US WECC California Region (Series 67)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 210.4,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-003-067",
        "emission_source_name": "Grid Electricity - US RFC East Mid-Atlantic (Series 68)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 325.8,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-004-068",
        "emission_source_name": "Grid Electricity - UK National Grid Average (Series 69)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 198.5,
        "reference_standard_source": "UK DEFRA GHG Guidelines",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-005-069",
        "emission_source_name": "Grid Electricity - Germany Federal Grid Mix (Series 70)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 345.0,
        "reference_standard_source": "UBA German Environment Agency",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-001-070",
        "emission_source_name": "Air Freight Cargo - Long Haul International (Series 71)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.602,
        "reference_standard_source": "ICAO Carbon Calculator",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-002-071",
        "emission_source_name": "Ocean Freight - Container Vessel FCL (Series 72)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.016,
        "reference_standard_source": "Clean Cargo Working Group",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-003-072",
        "emission_source_name": "Road Freight Truckload - Class 8 Heavy Truck (Series 73)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.105,
        "reference_standard_source": "SmartWay EPA Logistics",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-004-073",
        "emission_source_name": "Data Center Cloud Compute Server Hour (PUE 1.2) (Series 74)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Instance-hr",
        "emission_factor_kg_co2e_per_unit": 0.015,
        "reference_standard_source": "Cloud Carbon Footprint Methodology",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-005-074",
        "emission_source_name": "Virgin Aluminum Ingot Smelting Activity (Series 75)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 8.24,
        "reference_standard_source": "International Aluminium Institute",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-001-075",
        "emission_source_name": "Natural Gas Combustion (Industrial Boiler) (Series 76)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "MMBtu",
        "emission_factor_kg_co2e_per_unit": 53.06,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-002-076",
        "emission_source_name": "Diesel Fuel Combustion (Stationary Generator) (Series 77)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 10.21,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-003-077",
        "emission_source_name": "Motor Gasoline (Corporate Fleet Vehicles) (Series 78)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 8.78,
        "reference_standard_source": "EPA Climate Leaders",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-004-078",
        "emission_source_name": "Propane / LPG (Forklift & Warehouse Heating) (Series 79)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 5.72,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-005-079",
        "emission_source_name": "Refrigerant Fugitive Losses (R-410A HFC) (Series 80)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 2088.0,
        "reference_standard_source": "IPCC Fifth Assessment AR5",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-001-080",
        "emission_source_name": "Grid Electricity - US ERCOT Texas Region (Series 81)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 380.2,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-002-081",
        "emission_source_name": "Grid Electricity - US WECC California Region (Series 82)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 210.4,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-003-082",
        "emission_source_name": "Grid Electricity - US RFC East Mid-Atlantic (Series 83)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 325.8,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-004-083",
        "emission_source_name": "Grid Electricity - UK National Grid Average (Series 84)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 198.5,
        "reference_standard_source": "UK DEFRA GHG Guidelines",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-005-084",
        "emission_source_name": "Grid Electricity - Germany Federal Grid Mix (Series 85)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 345.0,
        "reference_standard_source": "UBA German Environment Agency",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-001-085",
        "emission_source_name": "Air Freight Cargo - Long Haul International (Series 86)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.602,
        "reference_standard_source": "ICAO Carbon Calculator",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-002-086",
        "emission_source_name": "Ocean Freight - Container Vessel FCL (Series 87)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.016,
        "reference_standard_source": "Clean Cargo Working Group",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-003-087",
        "emission_source_name": "Road Freight Truckload - Class 8 Heavy Truck (Series 88)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.105,
        "reference_standard_source": "SmartWay EPA Logistics",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-004-088",
        "emission_source_name": "Data Center Cloud Compute Server Hour (PUE 1.2) (Series 89)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Instance-hr",
        "emission_factor_kg_co2e_per_unit": 0.015,
        "reference_standard_source": "Cloud Carbon Footprint Methodology",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-005-089",
        "emission_source_name": "Virgin Aluminum Ingot Smelting Activity (Series 90)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 8.24,
        "reference_standard_source": "International Aluminium Institute",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-001-090",
        "emission_source_name": "Natural Gas Combustion (Industrial Boiler) (Series 91)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "MMBtu",
        "emission_factor_kg_co2e_per_unit": 53.06,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-002-091",
        "emission_source_name": "Diesel Fuel Combustion (Stationary Generator) (Series 92)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 10.21,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-003-092",
        "emission_source_name": "Motor Gasoline (Corporate Fleet Vehicles) (Series 93)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 8.78,
        "reference_standard_source": "EPA Climate Leaders",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-004-093",
        "emission_source_name": "Propane / LPG (Forklift & Warehouse Heating) (Series 94)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 5.72,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-005-094",
        "emission_source_name": "Refrigerant Fugitive Losses (R-410A HFC) (Series 95)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 2088.0,
        "reference_standard_source": "IPCC Fifth Assessment AR5",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-001-095",
        "emission_source_name": "Grid Electricity - US ERCOT Texas Region (Series 96)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 380.2,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-002-096",
        "emission_source_name": "Grid Electricity - US WECC California Region (Series 97)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 210.4,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-003-097",
        "emission_source_name": "Grid Electricity - US RFC East Mid-Atlantic (Series 98)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 325.8,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-004-098",
        "emission_source_name": "Grid Electricity - UK National Grid Average (Series 99)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 198.5,
        "reference_standard_source": "UK DEFRA GHG Guidelines",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-005-099",
        "emission_source_name": "Grid Electricity - Germany Federal Grid Mix (Series 100)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 345.0,
        "reference_standard_source": "UBA German Environment Agency",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-001-100",
        "emission_source_name": "Air Freight Cargo - Long Haul International (Series 101)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.602,
        "reference_standard_source": "ICAO Carbon Calculator",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-002-101",
        "emission_source_name": "Ocean Freight - Container Vessel FCL (Series 102)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.016,
        "reference_standard_source": "Clean Cargo Working Group",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-003-102",
        "emission_source_name": "Road Freight Truckload - Class 8 Heavy Truck (Series 103)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.105,
        "reference_standard_source": "SmartWay EPA Logistics",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-004-103",
        "emission_source_name": "Data Center Cloud Compute Server Hour (PUE 1.2) (Series 104)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Instance-hr",
        "emission_factor_kg_co2e_per_unit": 0.015,
        "reference_standard_source": "Cloud Carbon Footprint Methodology",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-005-104",
        "emission_source_name": "Virgin Aluminum Ingot Smelting Activity (Series 105)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 8.24,
        "reference_standard_source": "International Aluminium Institute",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-001-105",
        "emission_source_name": "Natural Gas Combustion (Industrial Boiler) (Series 106)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "MMBtu",
        "emission_factor_kg_co2e_per_unit": 53.06,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-002-106",
        "emission_source_name": "Diesel Fuel Combustion (Stationary Generator) (Series 107)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 10.21,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-003-107",
        "emission_source_name": "Motor Gasoline (Corporate Fleet Vehicles) (Series 108)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 8.78,
        "reference_standard_source": "EPA Climate Leaders",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-004-108",
        "emission_source_name": "Propane / LPG (Forklift & Warehouse Heating) (Series 109)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 5.72,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-005-109",
        "emission_source_name": "Refrigerant Fugitive Losses (R-410A HFC) (Series 110)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 2088.0,
        "reference_standard_source": "IPCC Fifth Assessment AR5",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-001-110",
        "emission_source_name": "Grid Electricity - US ERCOT Texas Region (Series 111)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 380.2,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-002-111",
        "emission_source_name": "Grid Electricity - US WECC California Region (Series 112)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 210.4,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-003-112",
        "emission_source_name": "Grid Electricity - US RFC East Mid-Atlantic (Series 113)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 325.8,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-004-113",
        "emission_source_name": "Grid Electricity - UK National Grid Average (Series 114)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 198.5,
        "reference_standard_source": "UK DEFRA GHG Guidelines",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-005-114",
        "emission_source_name": "Grid Electricity - Germany Federal Grid Mix (Series 115)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 345.0,
        "reference_standard_source": "UBA German Environment Agency",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-001-115",
        "emission_source_name": "Air Freight Cargo - Long Haul International (Series 116)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.602,
        "reference_standard_source": "ICAO Carbon Calculator",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-002-116",
        "emission_source_name": "Ocean Freight - Container Vessel FCL (Series 117)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.016,
        "reference_standard_source": "Clean Cargo Working Group",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-003-117",
        "emission_source_name": "Road Freight Truckload - Class 8 Heavy Truck (Series 118)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.105,
        "reference_standard_source": "SmartWay EPA Logistics",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-004-118",
        "emission_source_name": "Data Center Cloud Compute Server Hour (PUE 1.2) (Series 119)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Instance-hr",
        "emission_factor_kg_co2e_per_unit": 0.015,
        "reference_standard_source": "Cloud Carbon Footprint Methodology",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-005-119",
        "emission_source_name": "Virgin Aluminum Ingot Smelting Activity (Series 120)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 8.24,
        "reference_standard_source": "International Aluminium Institute",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-001-120",
        "emission_source_name": "Natural Gas Combustion (Industrial Boiler) (Series 121)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "MMBtu",
        "emission_factor_kg_co2e_per_unit": 53.06,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-002-121",
        "emission_source_name": "Diesel Fuel Combustion (Stationary Generator) (Series 122)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 10.21,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-003-122",
        "emission_source_name": "Motor Gasoline (Corporate Fleet Vehicles) (Series 123)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 8.78,
        "reference_standard_source": "EPA Climate Leaders",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-004-123",
        "emission_source_name": "Propane / LPG (Forklift & Warehouse Heating) (Series 124)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 5.72,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-005-124",
        "emission_source_name": "Refrigerant Fugitive Losses (R-410A HFC) (Series 125)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 2088.0,
        "reference_standard_source": "IPCC Fifth Assessment AR5",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-001-125",
        "emission_source_name": "Grid Electricity - US ERCOT Texas Region (Series 126)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 380.2,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-002-126",
        "emission_source_name": "Grid Electricity - US WECC California Region (Series 127)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 210.4,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-003-127",
        "emission_source_name": "Grid Electricity - US RFC East Mid-Atlantic (Series 128)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 325.8,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-004-128",
        "emission_source_name": "Grid Electricity - UK National Grid Average (Series 129)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 198.5,
        "reference_standard_source": "UK DEFRA GHG Guidelines",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-005-129",
        "emission_source_name": "Grid Electricity - Germany Federal Grid Mix (Series 130)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 345.0,
        "reference_standard_source": "UBA German Environment Agency",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-001-130",
        "emission_source_name": "Air Freight Cargo - Long Haul International (Series 131)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.602,
        "reference_standard_source": "ICAO Carbon Calculator",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-002-131",
        "emission_source_name": "Ocean Freight - Container Vessel FCL (Series 132)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.016,
        "reference_standard_source": "Clean Cargo Working Group",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-003-132",
        "emission_source_name": "Road Freight Truckload - Class 8 Heavy Truck (Series 133)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.105,
        "reference_standard_source": "SmartWay EPA Logistics",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-004-133",
        "emission_source_name": "Data Center Cloud Compute Server Hour (PUE 1.2) (Series 134)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Instance-hr",
        "emission_factor_kg_co2e_per_unit": 0.015,
        "reference_standard_source": "Cloud Carbon Footprint Methodology",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-005-134",
        "emission_source_name": "Virgin Aluminum Ingot Smelting Activity (Series 135)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 8.24,
        "reference_standard_source": "International Aluminium Institute",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-001-135",
        "emission_source_name": "Natural Gas Combustion (Industrial Boiler) (Series 136)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "MMBtu",
        "emission_factor_kg_co2e_per_unit": 53.06,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-002-136",
        "emission_source_name": "Diesel Fuel Combustion (Stationary Generator) (Series 137)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 10.21,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-003-137",
        "emission_source_name": "Motor Gasoline (Corporate Fleet Vehicles) (Series 138)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 8.78,
        "reference_standard_source": "EPA Climate Leaders",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-004-138",
        "emission_source_name": "Propane / LPG (Forklift & Warehouse Heating) (Series 139)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 5.72,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-005-139",
        "emission_source_name": "Refrigerant Fugitive Losses (R-410A HFC) (Series 140)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 2088.0,
        "reference_standard_source": "IPCC Fifth Assessment AR5",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-001-140",
        "emission_source_name": "Grid Electricity - US ERCOT Texas Region (Series 141)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 380.2,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-002-141",
        "emission_source_name": "Grid Electricity - US WECC California Region (Series 142)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 210.4,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-003-142",
        "emission_source_name": "Grid Electricity - US RFC East Mid-Atlantic (Series 143)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 325.8,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-004-143",
        "emission_source_name": "Grid Electricity - UK National Grid Average (Series 144)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 198.5,
        "reference_standard_source": "UK DEFRA GHG Guidelines",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-005-144",
        "emission_source_name": "Grid Electricity - Germany Federal Grid Mix (Series 145)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 345.0,
        "reference_standard_source": "UBA German Environment Agency",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-001-145",
        "emission_source_name": "Air Freight Cargo - Long Haul International (Series 146)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.602,
        "reference_standard_source": "ICAO Carbon Calculator",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-002-146",
        "emission_source_name": "Ocean Freight - Container Vessel FCL (Series 147)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.016,
        "reference_standard_source": "Clean Cargo Working Group",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-003-147",
        "emission_source_name": "Road Freight Truckload - Class 8 Heavy Truck (Series 148)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Tonne-km",
        "emission_factor_kg_co2e_per_unit": 0.105,
        "reference_standard_source": "SmartWay EPA Logistics",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-004-148",
        "emission_source_name": "Data Center Cloud Compute Server Hour (PUE 1.2) (Series 149)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Instance-hr",
        "emission_factor_kg_co2e_per_unit": 0.015,
        "reference_standard_source": "Cloud Carbon Footprint Methodology",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC3-005-149",
        "emission_source_name": "Virgin Aluminum Ingot Smelting Activity (Series 150)",
        "ghg_scope": "SCOPE_3_VALUE_CHAIN",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 8.24,
        "reference_standard_source": "International Aluminium Institute",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-001-150",
        "emission_source_name": "Natural Gas Combustion (Industrial Boiler) (Series 151)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "MMBtu",
        "emission_factor_kg_co2e_per_unit": 53.06,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-002-151",
        "emission_source_name": "Diesel Fuel Combustion (Stationary Generator) (Series 152)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 10.21,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-003-152",
        "emission_source_name": "Motor Gasoline (Corporate Fleet Vehicles) (Series 153)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 8.78,
        "reference_standard_source": "EPA Climate Leaders",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-004-153",
        "emission_source_name": "Propane / LPG (Forklift & Warehouse Heating) (Series 154)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Gallon",
        "emission_factor_kg_co2e_per_unit": 5.72,
        "reference_standard_source": "EPA Emission Factors Hub",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC1-005-154",
        "emission_source_name": "Refrigerant Fugitive Losses (R-410A HFC) (Series 155)",
        "ghg_scope": "SCOPE_1_DIRECT",
        "unit_of_measure": "Kilogram",
        "emission_factor_kg_co2e_per_unit": 2088.0,
        "reference_standard_source": "IPCC Fifth Assessment AR5",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-001-155",
        "emission_source_name": "Grid Electricity - US ERCOT Texas Region (Series 156)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 380.2,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-002-156",
        "emission_source_name": "Grid Electricity - US WECC California Region (Series 157)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 210.4,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-003-157",
        "emission_source_name": "Grid Electricity - US RFC East Mid-Atlantic (Series 158)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 325.8,
        "reference_standard_source": "EPA eGRID 2026 Subregion",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-004-158",
        "emission_source_name": "Grid Electricity - UK National Grid Average (Series 159)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 198.5,
        "reference_standard_source": "UK DEFRA GHG Guidelines",
        "is_verified_standard": True,
    },
    {
        "factor_id": "GHG-SC2-005-159",
        "emission_source_name": "Grid Electricity - Germany Federal Grid Mix (Series 160)",
        "ghg_scope": "SCOPE_2_LOCATION",
        "unit_of_measure": "MWh",
        "emission_factor_kg_co2e_per_unit": 345.0,
        "reference_standard_source": "UBA German Environment Agency",
        "is_verified_standard": True,
    },
]
