"""
Global Trade Compliance, OFAC SDN, and BIS Denied Parties Screening Matrix.
Includes fuzzy match heuristics and PEP politically exposed persons watchlist.
"""

GLOBAL_TRADE_SANCTIONS_MATRIX = [
    {
        "sanction_entry_id": "SDN-US-10928-000",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 1",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-001",
        "target_legal_name": "Alexander Petrovich Volkov - Division 2",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-002",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 3",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-003",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 4",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-004",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 5",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-005",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 6",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-006",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 7",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-007",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 8",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-008",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 9",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-009",
        "target_legal_name": "Alexander Petrovich Volkov - Division 10",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-010",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 11",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-011",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 12",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-012",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 13",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-013",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 14",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-014",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 15",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-015",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 16",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-016",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 17",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-017",
        "target_legal_name": "Alexander Petrovich Volkov - Division 18",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-018",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 19",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-019",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 20",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-020",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 21",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-021",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 22",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-022",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 23",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-023",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 24",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-024",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 25",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-025",
        "target_legal_name": "Alexander Petrovich Volkov - Division 26",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-026",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 27",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-027",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 28",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-028",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 29",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-029",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 30",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-030",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 31",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-031",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 32",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-032",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 33",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-033",
        "target_legal_name": "Alexander Petrovich Volkov - Division 34",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-034",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 35",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-035",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 36",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-036",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 37",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-037",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 38",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-038",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 39",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-039",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 40",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-040",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 41",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-041",
        "target_legal_name": "Alexander Petrovich Volkov - Division 42",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-042",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 43",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-043",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 44",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-044",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 45",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-045",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 46",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-046",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 47",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-047",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 48",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-048",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 49",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-049",
        "target_legal_name": "Alexander Petrovich Volkov - Division 50",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-050",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 51",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-051",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 52",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-052",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 53",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-053",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 54",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-054",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 55",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-055",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 56",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-056",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 57",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-057",
        "target_legal_name": "Alexander Petrovich Volkov - Division 58",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-058",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 59",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-059",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 60",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-060",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 61",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-061",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 62",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-062",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 63",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-063",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 64",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-064",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 65",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-065",
        "target_legal_name": "Alexander Petrovich Volkov - Division 66",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-066",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 67",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-067",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 68",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-068",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 69",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-069",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 70",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-070",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 71",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-071",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 72",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-072",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 73",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-073",
        "target_legal_name": "Alexander Petrovich Volkov - Division 74",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-074",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 75",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-075",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 76",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-076",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 77",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-077",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 78",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-078",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 79",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-079",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 80",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-080",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 81",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-081",
        "target_legal_name": "Alexander Petrovich Volkov - Division 82",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-082",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 83",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-083",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 84",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-084",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 85",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-085",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 86",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-086",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 87",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-087",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 88",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-088",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 89",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-089",
        "target_legal_name": "Alexander Petrovich Volkov - Division 90",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-090",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 91",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-091",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 92",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-092",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 93",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-093",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 94",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-094",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 95",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-095",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 96",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-096",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 97",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-097",
        "target_legal_name": "Alexander Petrovich Volkov - Division 98",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-098",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 99",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-099",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 100",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-100",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 101",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-101",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 102",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-102",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 103",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-103",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 104",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-104",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 105",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-105",
        "target_legal_name": "Alexander Petrovich Volkov - Division 106",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-106",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 107",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-107",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 108",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-108",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 109",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-109",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 110",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-110",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 111",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-111",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 112",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-112",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 113",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-113",
        "target_legal_name": "Alexander Petrovich Volkov - Division 114",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-114",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 115",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-115",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 116",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-116",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 117",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-117",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 118",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-118",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 119",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-119",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 120",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-120",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 121",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-121",
        "target_legal_name": "Alexander Petrovich Volkov - Division 122",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-122",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 123",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-123",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 124",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-124",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 125",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-125",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 126",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-126",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 127",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-127",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 128",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-128",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 129",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-129",
        "target_legal_name": "Alexander Petrovich Volkov - Division 130",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-130",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 131",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-131",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 132",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-132",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 133",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-133",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 134",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-134",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 135",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-135",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 136",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-136",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 137",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-137",
        "target_legal_name": "Alexander Petrovich Volkov - Division 138",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-138",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 139",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-139",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 140",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-140",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 141",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-141",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 142",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-142",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 143",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-143",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 144",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-144",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 145",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-145",
        "target_legal_name": "Alexander Petrovich Volkov - Division 146",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-146",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 147",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-147",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 148",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-148",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 149",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-149",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 150",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-150",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 151",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-151",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 152",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10928-152",
        "target_legal_name": "Trans-Continental Petrochemical Supply Ltd - Division 153",
        "entity_type": "ENTITY",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "IRAN_SANCTIONS",
        "match_threshold_tolerance": 0.95,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "SDN-US-10929-153",
        "target_legal_name": "Alexander Petrovich Volkov - Division 154",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "OFAC_SDN",
        "sanctions_program": "UKRAINE_RUSSIA_EO14024",
        "match_threshold_tolerance": 0.98,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-EL-48201-154",
        "target_legal_name": "Sino-Tech Microelectronics Foundry Co - Division 155",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_ENTITY_LIST",
        "sanctions_program": "EXPORT_RESTRICTIONS_3A090",
        "match_threshold_tolerance": 0.99,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "EU-CSL-88214-155",
        "target_legal_name": "Red Sea Maritime Freight Logistics SARL - Division 156",
        "entity_type": "ENTITY",
        "watchlist_source": "EU_CONSOLIDATED_LIST",
        "sanctions_program": "MARITIME_EMBARGO",
        "match_threshold_tolerance": 0.92,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "UK-HMT-00912-156",
        "target_legal_name": "Dmitry Ivanovich Smirnov - Division 157",
        "entity_type": "INDIVIDUAL",
        "watchlist_source": "UK_HMT_SANCTIONS",
        "sanctions_program": "FINANCIAL_FREEZE",
        "match_threshold_tolerance": 0.97,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "OFAC-NSM-301-157",
        "target_legal_name": "Caspian Navigation Shipping LLC - Division 158",
        "entity_type": "VESSEL",
        "watchlist_source": "OFAC_SDN_VESSEL",
        "sanctions_program": "ILLICIT_OIL_PRICE_CAP",
        "match_threshold_tolerance": 0.96,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "BIS-UVL-1029-158",
        "target_legal_name": "Shenzhen Quantum Laser Optics Corp - Division 159",
        "entity_type": "ENTITY",
        "watchlist_source": "BIS_UNVERIFIED_LIST",
        "sanctions_program": "END_USER_CHECK_PENDING",
        "match_threshold_tolerance": 0.85,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
    {
        "sanction_entry_id": "PEP-GL-99201-159",
        "target_legal_name": "Minister of Mining and Natural Resources - Division 160",
        "entity_type": "PEP_POLITICAL",
        "watchlist_source": "GLOBAL_PEP_WATCHLIST",
        "sanctions_program": "ANTI_CORRUPTION_FCPA",
        "match_threshold_tolerance": 0.9,
        "is_active_block": True,
        "country_jurisdiction": "GLOBAL",
    },
]
