"""
ISO 14001 Environmental Management Systems (EMS) Audit Criteria Taxonomy.
Standard environmental aspects, impact ratings, legal requirements, and operational controls.
"""

ISO_14001_EMS_AUDIT_CRITERIA = [
    {
        "aspect_identifier": "ENV-ASP-01-000",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 1)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-001",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 2)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-002",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 3)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-003",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 4)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-004",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 5)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-005",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 6)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-006",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 7)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-007",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 8)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-008",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 9)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-009",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 10)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-010",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 11)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-011",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 12)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-012",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 13)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-013",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 14)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-014",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 15)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-015",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 16)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-016",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 17)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-017",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 18)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-018",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 19)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-019",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 20)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-020",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 21)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-021",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 22)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-022",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 23)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-023",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 24)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-024",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 25)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-025",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 26)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-026",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 27)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-027",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 28)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-028",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 29)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-029",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 30)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-030",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 31)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-031",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 32)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-032",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 33)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-033",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 34)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-034",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 35)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-035",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 36)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-036",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 37)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-037",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 38)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-038",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 39)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-039",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 40)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-040",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 41)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-041",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 42)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-042",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 43)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-043",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 44)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-044",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 45)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-045",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 46)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-046",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 47)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-047",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 48)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-048",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 49)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-049",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 50)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-050",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 51)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-051",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 52)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-052",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 53)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-053",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 54)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-054",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 55)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-055",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 56)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-056",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 57)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-057",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 58)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-058",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 59)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-059",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 60)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-060",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 61)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-061",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 62)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-062",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 63)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-063",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 64)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-064",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 65)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-065",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 66)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-066",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 67)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-067",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 68)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-068",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 69)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-069",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 70)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-070",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 71)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-071",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 72)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-072",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 73)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-073",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 74)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-074",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 75)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-075",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 76)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-076",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 77)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-077",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 78)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-078",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 79)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-079",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 80)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-080",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 81)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-081",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 82)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-082",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 83)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-083",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 84)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-084",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 85)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-085",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 86)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-086",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 87)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-087",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 88)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-088",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 89)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-089",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 90)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-090",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 91)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-091",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 92)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-092",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 93)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-093",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 94)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-094",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 95)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-095",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 96)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-096",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 97)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-097",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 98)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-098",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 99)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-099",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 100)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-100",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 101)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-101",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 102)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-102",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 103)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-103",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 104)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-104",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 105)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-105",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 106)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-106",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 107)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-107",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 108)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-108",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 109)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-109",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 110)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-110",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 111)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-111",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 112)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-112",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 113)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-113",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 114)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-114",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 115)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-115",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 116)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-116",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 117)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-117",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 118)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-118",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 119)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-119",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 120)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-120",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 121)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-121",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 122)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-122",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 123)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-123",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 124)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-124",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 125)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-125",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 126)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-126",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 127)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-127",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 128)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-128",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 129)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-129",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 130)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-130",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 131)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-131",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 132)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-132",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 133)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-133",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 134)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-134",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 135)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-135",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 136)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-136",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 137)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-137",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 138)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-138",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 139)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-139",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 140)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-140",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 141)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-141",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 142)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-142",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 143)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-143",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 144)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-144",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 145)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-145",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 146)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-146",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 147)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-147",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 148)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-148",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 149)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-149",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 150)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-150",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 151)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-151",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 152)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-152",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 153)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-153",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 154)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-154",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 155)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-155",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 156)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-156",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 157)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-157",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 158)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-158",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 159)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-159",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 160)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-160",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 161)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-161",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 162)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-162",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 163)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-163",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 164)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-164",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 165)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-165",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 166)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-166",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 167)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-167",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 168)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-168",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 169)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-169",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 170)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-170",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 171)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-171",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 172)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-172",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 173)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-173",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 174)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-174",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 175)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-175",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 176)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-176",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 177)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-177",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 178)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-178",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 179)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-179",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 180)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-180",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 181)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-181",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 182)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-182",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 183)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-183",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 184)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-184",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 185)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-185",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 186)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-186",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 187)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-187",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 188)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-188",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 189)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-189",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 190)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-190",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 191)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-191",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 192)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-192",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 193)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-193",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 194)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-03-194",
        "environmental_aspect_title": "Industrial Wastewater Pretreatment & Discharge (Item 195)",
        "aspect_category": "WATER_CONSERVATION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "pH neutralization, heavy metal precipitation, and NPDES permitted municipal sewer discharge.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-04-195",
        "environmental_aspect_title": "Hazardous Waste Classification & Manifesting (Item 196)",
        "aspect_category": "WASTE_MANAGEMENT",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "RCRA hazardous waste generator tracking, EPA manifest logging, and 90-day storage limits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-05-196",
        "environmental_aspect_title": "Solid Waste Recycling & Landfill Diversion (Item 197)",
        "aspect_category": "CIRCULAR_ECONOMY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Segregated cardboard, metal scrap, and electronic scrap recycling to reach >90% zero-landfill.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-06-197",
        "environmental_aspect_title": "Facility Energy Conservation & Heat Recovery (Item 198)",
        "aspect_category": "ENERGY_EFFICIENCY",
        "environmental_significance": "MEDIUM",
        "operational_control_procedure": "Variable frequency drives on HVAC compressors and waste heat economizers on curing ovens.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-01-198",
        "environmental_aspect_title": "Air Emissions from Process Stacks (Item 199)",
        "aspect_category": "AIR_QUALITY",
        "environmental_significance": "HIGH",
        "operational_control_procedure": "Monitoring of VOC, particulate matter, and NOx concentrations against EPA Title V permits.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
    {
        "aspect_identifier": "ENV-ASP-02-199",
        "environmental_aspect_title": "Hazardous Chemical Storage & Secondary Containment (Item 200)",
        "aspect_category": "SPILL_PREVENTION",
        "environmental_significance": "CRITICAL",
        "operational_control_procedure": "Double-walled containment basins, leak sensors, and SPCC spill countermeasure compliance.",
        "audit_cycle": "ANNUAL",
        "regulatory_compliance_mandate": True,
    },
]
