"""
ISO 20022 Financial Messaging & SWIFT MT Protocol Master Catalog.
Comprehensive XML element definitions, validation rules, and message structure mappings.
"""

ISO_20022_MESSAGE_CATALOG = [
    {
        "message_identifier": "pain.001.001.03.v1",
        "standard_description": "Customer Credit Transfer Initiation (Release 1)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Credit Transfer & Fedwire initiation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.002.001.03.v2",
        "standard_description": "Customer Payment Status Report (Release 2)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/OrgnlGrpInfAndSts/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "ACK/NACK payment rejection notices",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.008.001.02.v3",
        "standard_description": "Customer Direct Debit Initiation (Release 3)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/DrctDbtTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Core / B2B Direct Debit collection",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.008.001.02.v4",
        "standard_description": "Financial Institution Customer Credit Transfer (Release 4)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Real-Time Gross Settlement (RTGS)",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.009.001.02.v5",
        "standard_description": "Financial Institution Credit Transfer (Cover) (Release 5)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Interbank liquidity cover movements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.002.001.03.v6",
        "standard_description": "FI to FI Payment Status Report (Release 6)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "Automated clearinghouse settlement confirmation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.052.001.02.v7",
        "standard_description": "Bank-to-Customer Intraday Report (Release 7)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Rpt/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Real-time intraday cash balance updates",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.053.001.02.v8",
        "standard_description": "Bank-to-Customer End-of-Day Statement (Release 8)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Stmt/Ntry/NtryDtls",
        "is_initiating_payment": False,
        "primary_use_case": "Official electronic balance statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.054.001.02.v9",
        "standard_description": "Bank-to-Customer Debit/Credit Notification (Release 9)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Ntfctn/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Immediate wire receipt notification",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.056.001.01.v10",
        "standard_description": "Payment Cancellation Request (Recall) (Release 10)",
        "business_domain": "Cash Management Exceptions",
        "xml_root_xpath": "GrpHdr/Undrlyg/TxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Automated wire recall and fraud freeze",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT101.v11",
        "standard_description": "Request for Transfer (Swift Legacy) (Release 11)",
        "business_domain": "Corporate Treasury",
        "xml_root_xpath": ":20:,:28D:,:30:,:21:,:32B:,:50H:,:59:",
        "is_initiating_payment": True,
        "primary_use_case": "SWIFT MT101 corporate payment order",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT103.v12",
        "standard_description": "Single Customer Credit Transfer (Release 12)",
        "business_domain": "Commercial Banking",
        "xml_root_xpath": ":20:,:23B:,:32A:,:50K:,:57A:,:59:,:71A:",
        "is_initiating_payment": True,
        "primary_use_case": "Standard international cross-border wire",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT202.v13",
        "standard_description": "General Financial Institution Transfer (Release 13)",
        "business_domain": "Interbank Treasury",
        "xml_root_xpath": ":20:,:21:,:32A:,:52A:,:58A:",
        "is_initiating_payment": True,
        "primary_use_case": "Cover wire for MT103 settlements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT940.v14",
        "standard_description": "Customer Statement Message (Release 14)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:60F:,:61:,:86:,:62F:",
        "is_initiating_payment": False,
        "primary_use_case": "Electronic end-of-day bank statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT942.v15",
        "standard_description": "Interim Transaction Report (Release 15)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:34F:,:61:,:86:,:90D:",
        "is_initiating_payment": False,
        "primary_use_case": "Intraday sweep and balance snapshot",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.001.001.03.v16",
        "standard_description": "Customer Credit Transfer Initiation (Release 16)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Credit Transfer & Fedwire initiation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.002.001.03.v17",
        "standard_description": "Customer Payment Status Report (Release 17)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/OrgnlGrpInfAndSts/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "ACK/NACK payment rejection notices",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.008.001.02.v18",
        "standard_description": "Customer Direct Debit Initiation (Release 18)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/DrctDbtTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Core / B2B Direct Debit collection",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.008.001.02.v19",
        "standard_description": "Financial Institution Customer Credit Transfer (Release 19)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Real-Time Gross Settlement (RTGS)",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.009.001.02.v20",
        "standard_description": "Financial Institution Credit Transfer (Cover) (Release 20)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Interbank liquidity cover movements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.002.001.03.v21",
        "standard_description": "FI to FI Payment Status Report (Release 21)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "Automated clearinghouse settlement confirmation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.052.001.02.v22",
        "standard_description": "Bank-to-Customer Intraday Report (Release 22)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Rpt/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Real-time intraday cash balance updates",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.053.001.02.v23",
        "standard_description": "Bank-to-Customer End-of-Day Statement (Release 23)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Stmt/Ntry/NtryDtls",
        "is_initiating_payment": False,
        "primary_use_case": "Official electronic balance statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.054.001.02.v24",
        "standard_description": "Bank-to-Customer Debit/Credit Notification (Release 24)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Ntfctn/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Immediate wire receipt notification",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.056.001.01.v25",
        "standard_description": "Payment Cancellation Request (Recall) (Release 25)",
        "business_domain": "Cash Management Exceptions",
        "xml_root_xpath": "GrpHdr/Undrlyg/TxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Automated wire recall and fraud freeze",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT101.v26",
        "standard_description": "Request for Transfer (Swift Legacy) (Release 26)",
        "business_domain": "Corporate Treasury",
        "xml_root_xpath": ":20:,:28D:,:30:,:21:,:32B:,:50H:,:59:",
        "is_initiating_payment": True,
        "primary_use_case": "SWIFT MT101 corporate payment order",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT103.v27",
        "standard_description": "Single Customer Credit Transfer (Release 27)",
        "business_domain": "Commercial Banking",
        "xml_root_xpath": ":20:,:23B:,:32A:,:50K:,:57A:,:59:,:71A:",
        "is_initiating_payment": True,
        "primary_use_case": "Standard international cross-border wire",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT202.v28",
        "standard_description": "General Financial Institution Transfer (Release 28)",
        "business_domain": "Interbank Treasury",
        "xml_root_xpath": ":20:,:21:,:32A:,:52A:,:58A:",
        "is_initiating_payment": True,
        "primary_use_case": "Cover wire for MT103 settlements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT940.v29",
        "standard_description": "Customer Statement Message (Release 29)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:60F:,:61:,:86:,:62F:",
        "is_initiating_payment": False,
        "primary_use_case": "Electronic end-of-day bank statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT942.v30",
        "standard_description": "Interim Transaction Report (Release 30)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:34F:,:61:,:86:,:90D:",
        "is_initiating_payment": False,
        "primary_use_case": "Intraday sweep and balance snapshot",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.001.001.03.v31",
        "standard_description": "Customer Credit Transfer Initiation (Release 31)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Credit Transfer & Fedwire initiation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.002.001.03.v32",
        "standard_description": "Customer Payment Status Report (Release 32)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/OrgnlGrpInfAndSts/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "ACK/NACK payment rejection notices",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.008.001.02.v33",
        "standard_description": "Customer Direct Debit Initiation (Release 33)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/DrctDbtTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Core / B2B Direct Debit collection",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.008.001.02.v34",
        "standard_description": "Financial Institution Customer Credit Transfer (Release 34)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Real-Time Gross Settlement (RTGS)",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.009.001.02.v35",
        "standard_description": "Financial Institution Credit Transfer (Cover) (Release 35)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Interbank liquidity cover movements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.002.001.03.v36",
        "standard_description": "FI to FI Payment Status Report (Release 36)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "Automated clearinghouse settlement confirmation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.052.001.02.v37",
        "standard_description": "Bank-to-Customer Intraday Report (Release 37)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Rpt/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Real-time intraday cash balance updates",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.053.001.02.v38",
        "standard_description": "Bank-to-Customer End-of-Day Statement (Release 38)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Stmt/Ntry/NtryDtls",
        "is_initiating_payment": False,
        "primary_use_case": "Official electronic balance statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.054.001.02.v39",
        "standard_description": "Bank-to-Customer Debit/Credit Notification (Release 39)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Ntfctn/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Immediate wire receipt notification",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.056.001.01.v40",
        "standard_description": "Payment Cancellation Request (Recall) (Release 40)",
        "business_domain": "Cash Management Exceptions",
        "xml_root_xpath": "GrpHdr/Undrlyg/TxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Automated wire recall and fraud freeze",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT101.v41",
        "standard_description": "Request for Transfer (Swift Legacy) (Release 41)",
        "business_domain": "Corporate Treasury",
        "xml_root_xpath": ":20:,:28D:,:30:,:21:,:32B:,:50H:,:59:",
        "is_initiating_payment": True,
        "primary_use_case": "SWIFT MT101 corporate payment order",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT103.v42",
        "standard_description": "Single Customer Credit Transfer (Release 42)",
        "business_domain": "Commercial Banking",
        "xml_root_xpath": ":20:,:23B:,:32A:,:50K:,:57A:,:59:,:71A:",
        "is_initiating_payment": True,
        "primary_use_case": "Standard international cross-border wire",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT202.v43",
        "standard_description": "General Financial Institution Transfer (Release 43)",
        "business_domain": "Interbank Treasury",
        "xml_root_xpath": ":20:,:21:,:32A:,:52A:,:58A:",
        "is_initiating_payment": True,
        "primary_use_case": "Cover wire for MT103 settlements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT940.v44",
        "standard_description": "Customer Statement Message (Release 44)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:60F:,:61:,:86:,:62F:",
        "is_initiating_payment": False,
        "primary_use_case": "Electronic end-of-day bank statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT942.v45",
        "standard_description": "Interim Transaction Report (Release 45)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:34F:,:61:,:86:,:90D:",
        "is_initiating_payment": False,
        "primary_use_case": "Intraday sweep and balance snapshot",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.001.001.03.v46",
        "standard_description": "Customer Credit Transfer Initiation (Release 46)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Credit Transfer & Fedwire initiation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.002.001.03.v47",
        "standard_description": "Customer Payment Status Report (Release 47)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/OrgnlGrpInfAndSts/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "ACK/NACK payment rejection notices",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.008.001.02.v48",
        "standard_description": "Customer Direct Debit Initiation (Release 48)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/DrctDbtTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Core / B2B Direct Debit collection",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.008.001.02.v49",
        "standard_description": "Financial Institution Customer Credit Transfer (Release 49)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Real-Time Gross Settlement (RTGS)",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.009.001.02.v50",
        "standard_description": "Financial Institution Credit Transfer (Cover) (Release 50)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Interbank liquidity cover movements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.002.001.03.v51",
        "standard_description": "FI to FI Payment Status Report (Release 51)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "Automated clearinghouse settlement confirmation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.052.001.02.v52",
        "standard_description": "Bank-to-Customer Intraday Report (Release 52)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Rpt/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Real-time intraday cash balance updates",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.053.001.02.v53",
        "standard_description": "Bank-to-Customer End-of-Day Statement (Release 53)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Stmt/Ntry/NtryDtls",
        "is_initiating_payment": False,
        "primary_use_case": "Official electronic balance statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.054.001.02.v54",
        "standard_description": "Bank-to-Customer Debit/Credit Notification (Release 54)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Ntfctn/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Immediate wire receipt notification",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.056.001.01.v55",
        "standard_description": "Payment Cancellation Request (Recall) (Release 55)",
        "business_domain": "Cash Management Exceptions",
        "xml_root_xpath": "GrpHdr/Undrlyg/TxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Automated wire recall and fraud freeze",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT101.v56",
        "standard_description": "Request for Transfer (Swift Legacy) (Release 56)",
        "business_domain": "Corporate Treasury",
        "xml_root_xpath": ":20:,:28D:,:30:,:21:,:32B:,:50H:,:59:",
        "is_initiating_payment": True,
        "primary_use_case": "SWIFT MT101 corporate payment order",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT103.v57",
        "standard_description": "Single Customer Credit Transfer (Release 57)",
        "business_domain": "Commercial Banking",
        "xml_root_xpath": ":20:,:23B:,:32A:,:50K:,:57A:,:59:,:71A:",
        "is_initiating_payment": True,
        "primary_use_case": "Standard international cross-border wire",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT202.v58",
        "standard_description": "General Financial Institution Transfer (Release 58)",
        "business_domain": "Interbank Treasury",
        "xml_root_xpath": ":20:,:21:,:32A:,:52A:,:58A:",
        "is_initiating_payment": True,
        "primary_use_case": "Cover wire for MT103 settlements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT940.v59",
        "standard_description": "Customer Statement Message (Release 59)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:60F:,:61:,:86:,:62F:",
        "is_initiating_payment": False,
        "primary_use_case": "Electronic end-of-day bank statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT942.v60",
        "standard_description": "Interim Transaction Report (Release 60)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:34F:,:61:,:86:,:90D:",
        "is_initiating_payment": False,
        "primary_use_case": "Intraday sweep and balance snapshot",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.001.001.03.v61",
        "standard_description": "Customer Credit Transfer Initiation (Release 61)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Credit Transfer & Fedwire initiation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.002.001.03.v62",
        "standard_description": "Customer Payment Status Report (Release 62)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/OrgnlGrpInfAndSts/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "ACK/NACK payment rejection notices",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.008.001.02.v63",
        "standard_description": "Customer Direct Debit Initiation (Release 63)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/DrctDbtTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Core / B2B Direct Debit collection",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.008.001.02.v64",
        "standard_description": "Financial Institution Customer Credit Transfer (Release 64)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Real-Time Gross Settlement (RTGS)",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.009.001.02.v65",
        "standard_description": "Financial Institution Credit Transfer (Cover) (Release 65)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Interbank liquidity cover movements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.002.001.03.v66",
        "standard_description": "FI to FI Payment Status Report (Release 66)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "Automated clearinghouse settlement confirmation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.052.001.02.v67",
        "standard_description": "Bank-to-Customer Intraday Report (Release 67)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Rpt/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Real-time intraday cash balance updates",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.053.001.02.v68",
        "standard_description": "Bank-to-Customer End-of-Day Statement (Release 68)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Stmt/Ntry/NtryDtls",
        "is_initiating_payment": False,
        "primary_use_case": "Official electronic balance statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.054.001.02.v69",
        "standard_description": "Bank-to-Customer Debit/Credit Notification (Release 69)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Ntfctn/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Immediate wire receipt notification",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.056.001.01.v70",
        "standard_description": "Payment Cancellation Request (Recall) (Release 70)",
        "business_domain": "Cash Management Exceptions",
        "xml_root_xpath": "GrpHdr/Undrlyg/TxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Automated wire recall and fraud freeze",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT101.v71",
        "standard_description": "Request for Transfer (Swift Legacy) (Release 71)",
        "business_domain": "Corporate Treasury",
        "xml_root_xpath": ":20:,:28D:,:30:,:21:,:32B:,:50H:,:59:",
        "is_initiating_payment": True,
        "primary_use_case": "SWIFT MT101 corporate payment order",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT103.v72",
        "standard_description": "Single Customer Credit Transfer (Release 72)",
        "business_domain": "Commercial Banking",
        "xml_root_xpath": ":20:,:23B:,:32A:,:50K:,:57A:,:59:,:71A:",
        "is_initiating_payment": True,
        "primary_use_case": "Standard international cross-border wire",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT202.v73",
        "standard_description": "General Financial Institution Transfer (Release 73)",
        "business_domain": "Interbank Treasury",
        "xml_root_xpath": ":20:,:21:,:32A:,:52A:,:58A:",
        "is_initiating_payment": True,
        "primary_use_case": "Cover wire for MT103 settlements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT940.v74",
        "standard_description": "Customer Statement Message (Release 74)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:60F:,:61:,:86:,:62F:",
        "is_initiating_payment": False,
        "primary_use_case": "Electronic end-of-day bank statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT942.v75",
        "standard_description": "Interim Transaction Report (Release 75)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:34F:,:61:,:86:,:90D:",
        "is_initiating_payment": False,
        "primary_use_case": "Intraday sweep and balance snapshot",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.001.001.03.v76",
        "standard_description": "Customer Credit Transfer Initiation (Release 76)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Credit Transfer & Fedwire initiation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.002.001.03.v77",
        "standard_description": "Customer Payment Status Report (Release 77)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/OrgnlGrpInfAndSts/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "ACK/NACK payment rejection notices",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.008.001.02.v78",
        "standard_description": "Customer Direct Debit Initiation (Release 78)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/DrctDbtTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Core / B2B Direct Debit collection",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.008.001.02.v79",
        "standard_description": "Financial Institution Customer Credit Transfer (Release 79)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Real-Time Gross Settlement (RTGS)",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.009.001.02.v80",
        "standard_description": "Financial Institution Credit Transfer (Cover) (Release 80)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Interbank liquidity cover movements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.002.001.03.v81",
        "standard_description": "FI to FI Payment Status Report (Release 81)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "Automated clearinghouse settlement confirmation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.052.001.02.v82",
        "standard_description": "Bank-to-Customer Intraday Report (Release 82)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Rpt/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Real-time intraday cash balance updates",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.053.001.02.v83",
        "standard_description": "Bank-to-Customer End-of-Day Statement (Release 83)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Stmt/Ntry/NtryDtls",
        "is_initiating_payment": False,
        "primary_use_case": "Official electronic balance statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.054.001.02.v84",
        "standard_description": "Bank-to-Customer Debit/Credit Notification (Release 84)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Ntfctn/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Immediate wire receipt notification",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.056.001.01.v85",
        "standard_description": "Payment Cancellation Request (Recall) (Release 85)",
        "business_domain": "Cash Management Exceptions",
        "xml_root_xpath": "GrpHdr/Undrlyg/TxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Automated wire recall and fraud freeze",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT101.v86",
        "standard_description": "Request for Transfer (Swift Legacy) (Release 86)",
        "business_domain": "Corporate Treasury",
        "xml_root_xpath": ":20:,:28D:,:30:,:21:,:32B:,:50H:,:59:",
        "is_initiating_payment": True,
        "primary_use_case": "SWIFT MT101 corporate payment order",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT103.v87",
        "standard_description": "Single Customer Credit Transfer (Release 87)",
        "business_domain": "Commercial Banking",
        "xml_root_xpath": ":20:,:23B:,:32A:,:50K:,:57A:,:59:,:71A:",
        "is_initiating_payment": True,
        "primary_use_case": "Standard international cross-border wire",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT202.v88",
        "standard_description": "General Financial Institution Transfer (Release 88)",
        "business_domain": "Interbank Treasury",
        "xml_root_xpath": ":20:,:21:,:32A:,:52A:,:58A:",
        "is_initiating_payment": True,
        "primary_use_case": "Cover wire for MT103 settlements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT940.v89",
        "standard_description": "Customer Statement Message (Release 89)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:60F:,:61:,:86:,:62F:",
        "is_initiating_payment": False,
        "primary_use_case": "Electronic end-of-day bank statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT942.v90",
        "standard_description": "Interim Transaction Report (Release 90)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:34F:,:61:,:86:,:90D:",
        "is_initiating_payment": False,
        "primary_use_case": "Intraday sweep and balance snapshot",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.001.001.03.v91",
        "standard_description": "Customer Credit Transfer Initiation (Release 91)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Credit Transfer & Fedwire initiation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.002.001.03.v92",
        "standard_description": "Customer Payment Status Report (Release 92)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/OrgnlGrpInfAndSts/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "ACK/NACK payment rejection notices",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.008.001.02.v93",
        "standard_description": "Customer Direct Debit Initiation (Release 93)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/DrctDbtTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Core / B2B Direct Debit collection",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.008.001.02.v94",
        "standard_description": "Financial Institution Customer Credit Transfer (Release 94)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Real-Time Gross Settlement (RTGS)",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.009.001.02.v95",
        "standard_description": "Financial Institution Credit Transfer (Cover) (Release 95)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Interbank liquidity cover movements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.002.001.03.v96",
        "standard_description": "FI to FI Payment Status Report (Release 96)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "Automated clearinghouse settlement confirmation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.052.001.02.v97",
        "standard_description": "Bank-to-Customer Intraday Report (Release 97)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Rpt/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Real-time intraday cash balance updates",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.053.001.02.v98",
        "standard_description": "Bank-to-Customer End-of-Day Statement (Release 98)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Stmt/Ntry/NtryDtls",
        "is_initiating_payment": False,
        "primary_use_case": "Official electronic balance statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.054.001.02.v99",
        "standard_description": "Bank-to-Customer Debit/Credit Notification (Release 99)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Ntfctn/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Immediate wire receipt notification",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.056.001.01.v100",
        "standard_description": "Payment Cancellation Request (Recall) (Release 100)",
        "business_domain": "Cash Management Exceptions",
        "xml_root_xpath": "GrpHdr/Undrlyg/TxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Automated wire recall and fraud freeze",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT101.v101",
        "standard_description": "Request for Transfer (Swift Legacy) (Release 101)",
        "business_domain": "Corporate Treasury",
        "xml_root_xpath": ":20:,:28D:,:30:,:21:,:32B:,:50H:,:59:",
        "is_initiating_payment": True,
        "primary_use_case": "SWIFT MT101 corporate payment order",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT103.v102",
        "standard_description": "Single Customer Credit Transfer (Release 102)",
        "business_domain": "Commercial Banking",
        "xml_root_xpath": ":20:,:23B:,:32A:,:50K:,:57A:,:59:,:71A:",
        "is_initiating_payment": True,
        "primary_use_case": "Standard international cross-border wire",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT202.v103",
        "standard_description": "General Financial Institution Transfer (Release 103)",
        "business_domain": "Interbank Treasury",
        "xml_root_xpath": ":20:,:21:,:32A:,:52A:,:58A:",
        "is_initiating_payment": True,
        "primary_use_case": "Cover wire for MT103 settlements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT940.v104",
        "standard_description": "Customer Statement Message (Release 104)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:60F:,:61:,:86:,:62F:",
        "is_initiating_payment": False,
        "primary_use_case": "Electronic end-of-day bank statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT942.v105",
        "standard_description": "Interim Transaction Report (Release 105)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:34F:,:61:,:86:,:90D:",
        "is_initiating_payment": False,
        "primary_use_case": "Intraday sweep and balance snapshot",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.001.001.03.v106",
        "standard_description": "Customer Credit Transfer Initiation (Release 106)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Credit Transfer & Fedwire initiation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.002.001.03.v107",
        "standard_description": "Customer Payment Status Report (Release 107)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/OrgnlGrpInfAndSts/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "ACK/NACK payment rejection notices",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.008.001.02.v108",
        "standard_description": "Customer Direct Debit Initiation (Release 108)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/DrctDbtTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Core / B2B Direct Debit collection",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.008.001.02.v109",
        "standard_description": "Financial Institution Customer Credit Transfer (Release 109)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Real-Time Gross Settlement (RTGS)",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.009.001.02.v110",
        "standard_description": "Financial Institution Credit Transfer (Cover) (Release 110)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Interbank liquidity cover movements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.002.001.03.v111",
        "standard_description": "FI to FI Payment Status Report (Release 111)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "Automated clearinghouse settlement confirmation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.052.001.02.v112",
        "standard_description": "Bank-to-Customer Intraday Report (Release 112)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Rpt/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Real-time intraday cash balance updates",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.053.001.02.v113",
        "standard_description": "Bank-to-Customer End-of-Day Statement (Release 113)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Stmt/Ntry/NtryDtls",
        "is_initiating_payment": False,
        "primary_use_case": "Official electronic balance statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.054.001.02.v114",
        "standard_description": "Bank-to-Customer Debit/Credit Notification (Release 114)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Ntfctn/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Immediate wire receipt notification",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.056.001.01.v115",
        "standard_description": "Payment Cancellation Request (Recall) (Release 115)",
        "business_domain": "Cash Management Exceptions",
        "xml_root_xpath": "GrpHdr/Undrlyg/TxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Automated wire recall and fraud freeze",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT101.v116",
        "standard_description": "Request for Transfer (Swift Legacy) (Release 116)",
        "business_domain": "Corporate Treasury",
        "xml_root_xpath": ":20:,:28D:,:30:,:21:,:32B:,:50H:,:59:",
        "is_initiating_payment": True,
        "primary_use_case": "SWIFT MT101 corporate payment order",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT103.v117",
        "standard_description": "Single Customer Credit Transfer (Release 117)",
        "business_domain": "Commercial Banking",
        "xml_root_xpath": ":20:,:23B:,:32A:,:50K:,:57A:,:59:,:71A:",
        "is_initiating_payment": True,
        "primary_use_case": "Standard international cross-border wire",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT202.v118",
        "standard_description": "General Financial Institution Transfer (Release 118)",
        "business_domain": "Interbank Treasury",
        "xml_root_xpath": ":20:,:21:,:32A:,:52A:,:58A:",
        "is_initiating_payment": True,
        "primary_use_case": "Cover wire for MT103 settlements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT940.v119",
        "standard_description": "Customer Statement Message (Release 119)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:60F:,:61:,:86:,:62F:",
        "is_initiating_payment": False,
        "primary_use_case": "Electronic end-of-day bank statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT942.v120",
        "standard_description": "Interim Transaction Report (Release 120)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:34F:,:61:,:86:,:90D:",
        "is_initiating_payment": False,
        "primary_use_case": "Intraday sweep and balance snapshot",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.001.001.03.v121",
        "standard_description": "Customer Credit Transfer Initiation (Release 121)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Credit Transfer & Fedwire initiation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.002.001.03.v122",
        "standard_description": "Customer Payment Status Report (Release 122)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/OrgnlGrpInfAndSts/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "ACK/NACK payment rejection notices",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.008.001.02.v123",
        "standard_description": "Customer Direct Debit Initiation (Release 123)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/DrctDbtTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Core / B2B Direct Debit collection",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.008.001.02.v124",
        "standard_description": "Financial Institution Customer Credit Transfer (Release 124)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Real-Time Gross Settlement (RTGS)",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.009.001.02.v125",
        "standard_description": "Financial Institution Credit Transfer (Cover) (Release 125)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Interbank liquidity cover movements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.002.001.03.v126",
        "standard_description": "FI to FI Payment Status Report (Release 126)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "Automated clearinghouse settlement confirmation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.052.001.02.v127",
        "standard_description": "Bank-to-Customer Intraday Report (Release 127)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Rpt/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Real-time intraday cash balance updates",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.053.001.02.v128",
        "standard_description": "Bank-to-Customer End-of-Day Statement (Release 128)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Stmt/Ntry/NtryDtls",
        "is_initiating_payment": False,
        "primary_use_case": "Official electronic balance statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.054.001.02.v129",
        "standard_description": "Bank-to-Customer Debit/Credit Notification (Release 129)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Ntfctn/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Immediate wire receipt notification",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.056.001.01.v130",
        "standard_description": "Payment Cancellation Request (Recall) (Release 130)",
        "business_domain": "Cash Management Exceptions",
        "xml_root_xpath": "GrpHdr/Undrlyg/TxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Automated wire recall and fraud freeze",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT101.v131",
        "standard_description": "Request for Transfer (Swift Legacy) (Release 131)",
        "business_domain": "Corporate Treasury",
        "xml_root_xpath": ":20:,:28D:,:30:,:21:,:32B:,:50H:,:59:",
        "is_initiating_payment": True,
        "primary_use_case": "SWIFT MT101 corporate payment order",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT103.v132",
        "standard_description": "Single Customer Credit Transfer (Release 132)",
        "business_domain": "Commercial Banking",
        "xml_root_xpath": ":20:,:23B:,:32A:,:50K:,:57A:,:59:,:71A:",
        "is_initiating_payment": True,
        "primary_use_case": "Standard international cross-border wire",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT202.v133",
        "standard_description": "General Financial Institution Transfer (Release 133)",
        "business_domain": "Interbank Treasury",
        "xml_root_xpath": ":20:,:21:,:32A:,:52A:,:58A:",
        "is_initiating_payment": True,
        "primary_use_case": "Cover wire for MT103 settlements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT940.v134",
        "standard_description": "Customer Statement Message (Release 134)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:60F:,:61:,:86:,:62F:",
        "is_initiating_payment": False,
        "primary_use_case": "Electronic end-of-day bank statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT942.v135",
        "standard_description": "Interim Transaction Report (Release 135)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:34F:,:61:,:86:,:90D:",
        "is_initiating_payment": False,
        "primary_use_case": "Intraday sweep and balance snapshot",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.001.001.03.v136",
        "standard_description": "Customer Credit Transfer Initiation (Release 136)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Credit Transfer & Fedwire initiation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.002.001.03.v137",
        "standard_description": "Customer Payment Status Report (Release 137)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/OrgnlGrpInfAndSts/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "ACK/NACK payment rejection notices",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.008.001.02.v138",
        "standard_description": "Customer Direct Debit Initiation (Release 138)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/DrctDbtTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Core / B2B Direct Debit collection",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.008.001.02.v139",
        "standard_description": "Financial Institution Customer Credit Transfer (Release 139)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Real-Time Gross Settlement (RTGS)",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.009.001.02.v140",
        "standard_description": "Financial Institution Credit Transfer (Cover) (Release 140)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Interbank liquidity cover movements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.002.001.03.v141",
        "standard_description": "FI to FI Payment Status Report (Release 141)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "Automated clearinghouse settlement confirmation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.052.001.02.v142",
        "standard_description": "Bank-to-Customer Intraday Report (Release 142)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Rpt/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Real-time intraday cash balance updates",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.053.001.02.v143",
        "standard_description": "Bank-to-Customer End-of-Day Statement (Release 143)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Stmt/Ntry/NtryDtls",
        "is_initiating_payment": False,
        "primary_use_case": "Official electronic balance statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.054.001.02.v144",
        "standard_description": "Bank-to-Customer Debit/Credit Notification (Release 144)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Ntfctn/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Immediate wire receipt notification",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.056.001.01.v145",
        "standard_description": "Payment Cancellation Request (Recall) (Release 145)",
        "business_domain": "Cash Management Exceptions",
        "xml_root_xpath": "GrpHdr/Undrlyg/TxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Automated wire recall and fraud freeze",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT101.v146",
        "standard_description": "Request for Transfer (Swift Legacy) (Release 146)",
        "business_domain": "Corporate Treasury",
        "xml_root_xpath": ":20:,:28D:,:30:,:21:,:32B:,:50H:,:59:",
        "is_initiating_payment": True,
        "primary_use_case": "SWIFT MT101 corporate payment order",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT103.v147",
        "standard_description": "Single Customer Credit Transfer (Release 147)",
        "business_domain": "Commercial Banking",
        "xml_root_xpath": ":20:,:23B:,:32A:,:50K:,:57A:,:59:,:71A:",
        "is_initiating_payment": True,
        "primary_use_case": "Standard international cross-border wire",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT202.v148",
        "standard_description": "General Financial Institution Transfer (Release 148)",
        "business_domain": "Interbank Treasury",
        "xml_root_xpath": ":20:,:21:,:32A:,:52A:,:58A:",
        "is_initiating_payment": True,
        "primary_use_case": "Cover wire for MT103 settlements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT940.v149",
        "standard_description": "Customer Statement Message (Release 149)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:60F:,:61:,:86:,:62F:",
        "is_initiating_payment": False,
        "primary_use_case": "Electronic end-of-day bank statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "MT942.v150",
        "standard_description": "Interim Transaction Report (Release 150)",
        "business_domain": "Electronic Reporting",
        "xml_root_xpath": ":20:,:25:,:28C:,:34F:,:61:,:86:,:90D:",
        "is_initiating_payment": False,
        "primary_use_case": "Intraday sweep and balance snapshot",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.001.001.03.v151",
        "standard_description": "Customer Credit Transfer Initiation (Release 151)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Credit Transfer & Fedwire initiation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.002.001.03.v152",
        "standard_description": "Customer Payment Status Report (Release 152)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/OrgnlGrpInfAndSts/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "ACK/NACK payment rejection notices",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pain.008.001.02.v153",
        "standard_description": "Customer Direct Debit Initiation (Release 153)",
        "business_domain": "Payments & Cash Management",
        "xml_root_xpath": "GrpHdr/PmtInf/DrctDbtTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "SEPA Core / B2B Direct Debit collection",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.008.001.02.v154",
        "standard_description": "Financial Institution Customer Credit Transfer (Release 154)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Real-Time Gross Settlement (RTGS)",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.009.001.02.v155",
        "standard_description": "Financial Institution Credit Transfer (Cover) (Release 155)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/CdtTrfTxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Interbank liquidity cover movements",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "pacs.002.001.03.v156",
        "standard_description": "FI to FI Payment Status Report (Release 156)",
        "business_domain": "Interbank Clearing",
        "xml_root_xpath": "GrpHdr/TxInfAndSts",
        "is_initiating_payment": False,
        "primary_use_case": "Automated clearinghouse settlement confirmation",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.052.001.02.v157",
        "standard_description": "Bank-to-Customer Intraday Report (Release 157)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Rpt/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Real-time intraday cash balance updates",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.053.001.02.v158",
        "standard_description": "Bank-to-Customer End-of-Day Statement (Release 158)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Stmt/Ntry/NtryDtls",
        "is_initiating_payment": False,
        "primary_use_case": "Official electronic balance statement",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.054.001.02.v159",
        "standard_description": "Bank-to-Customer Debit/Credit Notification (Release 159)",
        "business_domain": "Account Cash Management",
        "xml_root_xpath": "GrpHdr/Ntfctn/Ntry",
        "is_initiating_payment": False,
        "primary_use_case": "Immediate wire receipt notification",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
    {
        "message_identifier": "camt.056.001.01.v160",
        "standard_description": "Payment Cancellation Request (Recall) (Release 160)",
        "business_domain": "Cash Management Exceptions",
        "xml_root_xpath": "GrpHdr/Undrlyg/TxInf",
        "is_initiating_payment": True,
        "primary_use_case": "Automated wire recall and fraud freeze",
        "schema_version": "2026.1",
        "security_signing_required": True,
    },
]
