"""
North American Industry Classification System (NAICS) 2026 Reference Taxonomy.
Includes default ESG emissions intensity factor and credit default risk weighting.
"""

NAICS_INDUSTRY_TAXONOMY = [
    {
        "naics_code": "511210",
        "industry_title": "Software Publishers & Cloud SaaS Enterprise Platforms (Class 1)",
        "economic_sector": "Information Technology",
        "carbon_intensity_tco2e_per_revenue_million": 0.045,
        "historical_default_loss_rate": 0.012,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "541511",
        "industry_title": "Computer Systems Design and Enterprise Integration Services (Class 2)",
        "economic_sector": "Professional Services",
        "carbon_intensity_tco2e_per_revenue_million": 0.038,
        "historical_default_loss_rate": 0.015,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333122",
        "industry_title": "Construction Machinery & Heavy Equipment Manufacturing (Class 3)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.485,
        "historical_default_loss_rate": 0.035,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333513",
        "industry_title": "Machine Tool (Metal Cutting Types) Precision Manufacturing (Class 4)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.42,
        "historical_default_loss_rate": 0.028,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334414",
        "industry_title": "Printed Circuit Assembly (Electronic Assembly) Manufacturing (Class 5)",
        "economic_sector": "Electronics",
        "carbon_intensity_tco2e_per_revenue_million": 0.28,
        "historical_default_loss_rate": 0.022,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334515",
        "industry_title": "Instruments and Related Products for Measuring Industrial Variables (Class 6)",
        "economic_sector": "Instruments & Optics",
        "carbon_intensity_tco2e_per_revenue_million": 0.19,
        "historical_default_loss_rate": 0.018,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "493116",
        "industry_title": "General Warehousing and Distribution Logistics Storage (Class 7)",
        "economic_sector": "Transportation & Warehousing",
        "carbon_intensity_tco2e_per_revenue_million": 0.35,
        "historical_default_loss_rate": 0.024,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484117",
        "industry_title": "General Freight Trucking, Local Fleet Operations (Class 8)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 0.85,
        "historical_default_loss_rate": 0.042,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484128",
        "industry_title": "General Freight Trucking, Long-Distance Truckload (FTL) (Class 9)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 1.25,
        "historical_default_loss_rate": 0.048,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "423619",
        "industry_title": "Electrical Apparatus and Equipment, Wiring Supplies Wholesalers (Class 10)",
        "economic_sector": "Wholesale Trade",
        "carbon_intensity_tco2e_per_revenue_million": 0.12,
        "historical_default_loss_rate": 0.019,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "511210",
        "industry_title": "Software Publishers & Cloud SaaS Enterprise Platforms (Class 11)",
        "economic_sector": "Information Technology",
        "carbon_intensity_tco2e_per_revenue_million": 0.045,
        "historical_default_loss_rate": 0.012,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "541511",
        "industry_title": "Computer Systems Design and Enterprise Integration Services (Class 12)",
        "economic_sector": "Professional Services",
        "carbon_intensity_tco2e_per_revenue_million": 0.038,
        "historical_default_loss_rate": 0.015,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333122",
        "industry_title": "Construction Machinery & Heavy Equipment Manufacturing (Class 13)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.485,
        "historical_default_loss_rate": 0.035,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333513",
        "industry_title": "Machine Tool (Metal Cutting Types) Precision Manufacturing (Class 14)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.42,
        "historical_default_loss_rate": 0.028,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334414",
        "industry_title": "Printed Circuit Assembly (Electronic Assembly) Manufacturing (Class 15)",
        "economic_sector": "Electronics",
        "carbon_intensity_tco2e_per_revenue_million": 0.28,
        "historical_default_loss_rate": 0.022,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334515",
        "industry_title": "Instruments and Related Products for Measuring Industrial Variables (Class 16)",
        "economic_sector": "Instruments & Optics",
        "carbon_intensity_tco2e_per_revenue_million": 0.19,
        "historical_default_loss_rate": 0.018,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "493116",
        "industry_title": "General Warehousing and Distribution Logistics Storage (Class 17)",
        "economic_sector": "Transportation & Warehousing",
        "carbon_intensity_tco2e_per_revenue_million": 0.35,
        "historical_default_loss_rate": 0.024,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484117",
        "industry_title": "General Freight Trucking, Local Fleet Operations (Class 18)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 0.85,
        "historical_default_loss_rate": 0.042,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484128",
        "industry_title": "General Freight Trucking, Long-Distance Truckload (FTL) (Class 19)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 1.25,
        "historical_default_loss_rate": 0.048,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "423619",
        "industry_title": "Electrical Apparatus and Equipment, Wiring Supplies Wholesalers (Class 20)",
        "economic_sector": "Wholesale Trade",
        "carbon_intensity_tco2e_per_revenue_million": 0.12,
        "historical_default_loss_rate": 0.019,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "511210",
        "industry_title": "Software Publishers & Cloud SaaS Enterprise Platforms (Class 21)",
        "economic_sector": "Information Technology",
        "carbon_intensity_tco2e_per_revenue_million": 0.045,
        "historical_default_loss_rate": 0.012,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "541511",
        "industry_title": "Computer Systems Design and Enterprise Integration Services (Class 22)",
        "economic_sector": "Professional Services",
        "carbon_intensity_tco2e_per_revenue_million": 0.038,
        "historical_default_loss_rate": 0.015,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333122",
        "industry_title": "Construction Machinery & Heavy Equipment Manufacturing (Class 23)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.485,
        "historical_default_loss_rate": 0.035,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333513",
        "industry_title": "Machine Tool (Metal Cutting Types) Precision Manufacturing (Class 24)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.42,
        "historical_default_loss_rate": 0.028,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334414",
        "industry_title": "Printed Circuit Assembly (Electronic Assembly) Manufacturing (Class 25)",
        "economic_sector": "Electronics",
        "carbon_intensity_tco2e_per_revenue_million": 0.28,
        "historical_default_loss_rate": 0.022,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334515",
        "industry_title": "Instruments and Related Products for Measuring Industrial Variables (Class 26)",
        "economic_sector": "Instruments & Optics",
        "carbon_intensity_tco2e_per_revenue_million": 0.19,
        "historical_default_loss_rate": 0.018,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "493116",
        "industry_title": "General Warehousing and Distribution Logistics Storage (Class 27)",
        "economic_sector": "Transportation & Warehousing",
        "carbon_intensity_tco2e_per_revenue_million": 0.35,
        "historical_default_loss_rate": 0.024,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484117",
        "industry_title": "General Freight Trucking, Local Fleet Operations (Class 28)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 0.85,
        "historical_default_loss_rate": 0.042,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484128",
        "industry_title": "General Freight Trucking, Long-Distance Truckload (FTL) (Class 29)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 1.25,
        "historical_default_loss_rate": 0.048,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "423619",
        "industry_title": "Electrical Apparatus and Equipment, Wiring Supplies Wholesalers (Class 30)",
        "economic_sector": "Wholesale Trade",
        "carbon_intensity_tco2e_per_revenue_million": 0.12,
        "historical_default_loss_rate": 0.019,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "511210",
        "industry_title": "Software Publishers & Cloud SaaS Enterprise Platforms (Class 31)",
        "economic_sector": "Information Technology",
        "carbon_intensity_tco2e_per_revenue_million": 0.045,
        "historical_default_loss_rate": 0.012,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "541511",
        "industry_title": "Computer Systems Design and Enterprise Integration Services (Class 32)",
        "economic_sector": "Professional Services",
        "carbon_intensity_tco2e_per_revenue_million": 0.038,
        "historical_default_loss_rate": 0.015,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333122",
        "industry_title": "Construction Machinery & Heavy Equipment Manufacturing (Class 33)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.485,
        "historical_default_loss_rate": 0.035,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333513",
        "industry_title": "Machine Tool (Metal Cutting Types) Precision Manufacturing (Class 34)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.42,
        "historical_default_loss_rate": 0.028,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334414",
        "industry_title": "Printed Circuit Assembly (Electronic Assembly) Manufacturing (Class 35)",
        "economic_sector": "Electronics",
        "carbon_intensity_tco2e_per_revenue_million": 0.28,
        "historical_default_loss_rate": 0.022,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334515",
        "industry_title": "Instruments and Related Products for Measuring Industrial Variables (Class 36)",
        "economic_sector": "Instruments & Optics",
        "carbon_intensity_tco2e_per_revenue_million": 0.19,
        "historical_default_loss_rate": 0.018,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "493116",
        "industry_title": "General Warehousing and Distribution Logistics Storage (Class 37)",
        "economic_sector": "Transportation & Warehousing",
        "carbon_intensity_tco2e_per_revenue_million": 0.35,
        "historical_default_loss_rate": 0.024,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484117",
        "industry_title": "General Freight Trucking, Local Fleet Operations (Class 38)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 0.85,
        "historical_default_loss_rate": 0.042,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484128",
        "industry_title": "General Freight Trucking, Long-Distance Truckload (FTL) (Class 39)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 1.25,
        "historical_default_loss_rate": 0.048,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "423619",
        "industry_title": "Electrical Apparatus and Equipment, Wiring Supplies Wholesalers (Class 40)",
        "economic_sector": "Wholesale Trade",
        "carbon_intensity_tco2e_per_revenue_million": 0.12,
        "historical_default_loss_rate": 0.019,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "511210",
        "industry_title": "Software Publishers & Cloud SaaS Enterprise Platforms (Class 41)",
        "economic_sector": "Information Technology",
        "carbon_intensity_tco2e_per_revenue_million": 0.045,
        "historical_default_loss_rate": 0.012,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "541511",
        "industry_title": "Computer Systems Design and Enterprise Integration Services (Class 42)",
        "economic_sector": "Professional Services",
        "carbon_intensity_tco2e_per_revenue_million": 0.038,
        "historical_default_loss_rate": 0.015,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333122",
        "industry_title": "Construction Machinery & Heavy Equipment Manufacturing (Class 43)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.485,
        "historical_default_loss_rate": 0.035,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333513",
        "industry_title": "Machine Tool (Metal Cutting Types) Precision Manufacturing (Class 44)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.42,
        "historical_default_loss_rate": 0.028,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334414",
        "industry_title": "Printed Circuit Assembly (Electronic Assembly) Manufacturing (Class 45)",
        "economic_sector": "Electronics",
        "carbon_intensity_tco2e_per_revenue_million": 0.28,
        "historical_default_loss_rate": 0.022,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334515",
        "industry_title": "Instruments and Related Products for Measuring Industrial Variables (Class 46)",
        "economic_sector": "Instruments & Optics",
        "carbon_intensity_tco2e_per_revenue_million": 0.19,
        "historical_default_loss_rate": 0.018,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "493116",
        "industry_title": "General Warehousing and Distribution Logistics Storage (Class 47)",
        "economic_sector": "Transportation & Warehousing",
        "carbon_intensity_tco2e_per_revenue_million": 0.35,
        "historical_default_loss_rate": 0.024,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484117",
        "industry_title": "General Freight Trucking, Local Fleet Operations (Class 48)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 0.85,
        "historical_default_loss_rate": 0.042,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484128",
        "industry_title": "General Freight Trucking, Long-Distance Truckload (FTL) (Class 49)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 1.25,
        "historical_default_loss_rate": 0.048,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "423619",
        "industry_title": "Electrical Apparatus and Equipment, Wiring Supplies Wholesalers (Class 50)",
        "economic_sector": "Wholesale Trade",
        "carbon_intensity_tco2e_per_revenue_million": 0.12,
        "historical_default_loss_rate": 0.019,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "511210",
        "industry_title": "Software Publishers & Cloud SaaS Enterprise Platforms (Class 51)",
        "economic_sector": "Information Technology",
        "carbon_intensity_tco2e_per_revenue_million": 0.045,
        "historical_default_loss_rate": 0.012,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "541511",
        "industry_title": "Computer Systems Design and Enterprise Integration Services (Class 52)",
        "economic_sector": "Professional Services",
        "carbon_intensity_tco2e_per_revenue_million": 0.038,
        "historical_default_loss_rate": 0.015,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333122",
        "industry_title": "Construction Machinery & Heavy Equipment Manufacturing (Class 53)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.485,
        "historical_default_loss_rate": 0.035,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333513",
        "industry_title": "Machine Tool (Metal Cutting Types) Precision Manufacturing (Class 54)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.42,
        "historical_default_loss_rate": 0.028,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334414",
        "industry_title": "Printed Circuit Assembly (Electronic Assembly) Manufacturing (Class 55)",
        "economic_sector": "Electronics",
        "carbon_intensity_tco2e_per_revenue_million": 0.28,
        "historical_default_loss_rate": 0.022,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334515",
        "industry_title": "Instruments and Related Products for Measuring Industrial Variables (Class 56)",
        "economic_sector": "Instruments & Optics",
        "carbon_intensity_tco2e_per_revenue_million": 0.19,
        "historical_default_loss_rate": 0.018,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "493116",
        "industry_title": "General Warehousing and Distribution Logistics Storage (Class 57)",
        "economic_sector": "Transportation & Warehousing",
        "carbon_intensity_tco2e_per_revenue_million": 0.35,
        "historical_default_loss_rate": 0.024,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484117",
        "industry_title": "General Freight Trucking, Local Fleet Operations (Class 58)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 0.85,
        "historical_default_loss_rate": 0.042,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484128",
        "industry_title": "General Freight Trucking, Long-Distance Truckload (FTL) (Class 59)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 1.25,
        "historical_default_loss_rate": 0.048,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "423619",
        "industry_title": "Electrical Apparatus and Equipment, Wiring Supplies Wholesalers (Class 60)",
        "economic_sector": "Wholesale Trade",
        "carbon_intensity_tco2e_per_revenue_million": 0.12,
        "historical_default_loss_rate": 0.019,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "511210",
        "industry_title": "Software Publishers & Cloud SaaS Enterprise Platforms (Class 61)",
        "economic_sector": "Information Technology",
        "carbon_intensity_tco2e_per_revenue_million": 0.045,
        "historical_default_loss_rate": 0.012,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "541511",
        "industry_title": "Computer Systems Design and Enterprise Integration Services (Class 62)",
        "economic_sector": "Professional Services",
        "carbon_intensity_tco2e_per_revenue_million": 0.038,
        "historical_default_loss_rate": 0.015,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333122",
        "industry_title": "Construction Machinery & Heavy Equipment Manufacturing (Class 63)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.485,
        "historical_default_loss_rate": 0.035,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333513",
        "industry_title": "Machine Tool (Metal Cutting Types) Precision Manufacturing (Class 64)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.42,
        "historical_default_loss_rate": 0.028,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334414",
        "industry_title": "Printed Circuit Assembly (Electronic Assembly) Manufacturing (Class 65)",
        "economic_sector": "Electronics",
        "carbon_intensity_tco2e_per_revenue_million": 0.28,
        "historical_default_loss_rate": 0.022,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334515",
        "industry_title": "Instruments and Related Products for Measuring Industrial Variables (Class 66)",
        "economic_sector": "Instruments & Optics",
        "carbon_intensity_tco2e_per_revenue_million": 0.19,
        "historical_default_loss_rate": 0.018,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "493116",
        "industry_title": "General Warehousing and Distribution Logistics Storage (Class 67)",
        "economic_sector": "Transportation & Warehousing",
        "carbon_intensity_tco2e_per_revenue_million": 0.35,
        "historical_default_loss_rate": 0.024,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484117",
        "industry_title": "General Freight Trucking, Local Fleet Operations (Class 68)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 0.85,
        "historical_default_loss_rate": 0.042,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484128",
        "industry_title": "General Freight Trucking, Long-Distance Truckload (FTL) (Class 69)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 1.25,
        "historical_default_loss_rate": 0.048,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "423619",
        "industry_title": "Electrical Apparatus and Equipment, Wiring Supplies Wholesalers (Class 70)",
        "economic_sector": "Wholesale Trade",
        "carbon_intensity_tco2e_per_revenue_million": 0.12,
        "historical_default_loss_rate": 0.019,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "511210",
        "industry_title": "Software Publishers & Cloud SaaS Enterprise Platforms (Class 71)",
        "economic_sector": "Information Technology",
        "carbon_intensity_tco2e_per_revenue_million": 0.045,
        "historical_default_loss_rate": 0.012,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "541511",
        "industry_title": "Computer Systems Design and Enterprise Integration Services (Class 72)",
        "economic_sector": "Professional Services",
        "carbon_intensity_tco2e_per_revenue_million": 0.038,
        "historical_default_loss_rate": 0.015,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333122",
        "industry_title": "Construction Machinery & Heavy Equipment Manufacturing (Class 73)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.485,
        "historical_default_loss_rate": 0.035,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333513",
        "industry_title": "Machine Tool (Metal Cutting Types) Precision Manufacturing (Class 74)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.42,
        "historical_default_loss_rate": 0.028,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334414",
        "industry_title": "Printed Circuit Assembly (Electronic Assembly) Manufacturing (Class 75)",
        "economic_sector": "Electronics",
        "carbon_intensity_tco2e_per_revenue_million": 0.28,
        "historical_default_loss_rate": 0.022,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334515",
        "industry_title": "Instruments and Related Products for Measuring Industrial Variables (Class 76)",
        "economic_sector": "Instruments & Optics",
        "carbon_intensity_tco2e_per_revenue_million": 0.19,
        "historical_default_loss_rate": 0.018,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "493116",
        "industry_title": "General Warehousing and Distribution Logistics Storage (Class 77)",
        "economic_sector": "Transportation & Warehousing",
        "carbon_intensity_tco2e_per_revenue_million": 0.35,
        "historical_default_loss_rate": 0.024,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484117",
        "industry_title": "General Freight Trucking, Local Fleet Operations (Class 78)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 0.85,
        "historical_default_loss_rate": 0.042,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484128",
        "industry_title": "General Freight Trucking, Long-Distance Truckload (FTL) (Class 79)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 1.25,
        "historical_default_loss_rate": 0.048,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "423619",
        "industry_title": "Electrical Apparatus and Equipment, Wiring Supplies Wholesalers (Class 80)",
        "economic_sector": "Wholesale Trade",
        "carbon_intensity_tco2e_per_revenue_million": 0.12,
        "historical_default_loss_rate": 0.019,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "511210",
        "industry_title": "Software Publishers & Cloud SaaS Enterprise Platforms (Class 81)",
        "economic_sector": "Information Technology",
        "carbon_intensity_tco2e_per_revenue_million": 0.045,
        "historical_default_loss_rate": 0.012,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "541511",
        "industry_title": "Computer Systems Design and Enterprise Integration Services (Class 82)",
        "economic_sector": "Professional Services",
        "carbon_intensity_tco2e_per_revenue_million": 0.038,
        "historical_default_loss_rate": 0.015,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333122",
        "industry_title": "Construction Machinery & Heavy Equipment Manufacturing (Class 83)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.485,
        "historical_default_loss_rate": 0.035,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333513",
        "industry_title": "Machine Tool (Metal Cutting Types) Precision Manufacturing (Class 84)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.42,
        "historical_default_loss_rate": 0.028,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334414",
        "industry_title": "Printed Circuit Assembly (Electronic Assembly) Manufacturing (Class 85)",
        "economic_sector": "Electronics",
        "carbon_intensity_tco2e_per_revenue_million": 0.28,
        "historical_default_loss_rate": 0.022,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334515",
        "industry_title": "Instruments and Related Products for Measuring Industrial Variables (Class 86)",
        "economic_sector": "Instruments & Optics",
        "carbon_intensity_tco2e_per_revenue_million": 0.19,
        "historical_default_loss_rate": 0.018,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "493116",
        "industry_title": "General Warehousing and Distribution Logistics Storage (Class 87)",
        "economic_sector": "Transportation & Warehousing",
        "carbon_intensity_tco2e_per_revenue_million": 0.35,
        "historical_default_loss_rate": 0.024,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484117",
        "industry_title": "General Freight Trucking, Local Fleet Operations (Class 88)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 0.85,
        "historical_default_loss_rate": 0.042,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484128",
        "industry_title": "General Freight Trucking, Long-Distance Truckload (FTL) (Class 89)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 1.25,
        "historical_default_loss_rate": 0.048,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "423619",
        "industry_title": "Electrical Apparatus and Equipment, Wiring Supplies Wholesalers (Class 90)",
        "economic_sector": "Wholesale Trade",
        "carbon_intensity_tco2e_per_revenue_million": 0.12,
        "historical_default_loss_rate": 0.019,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "511210",
        "industry_title": "Software Publishers & Cloud SaaS Enterprise Platforms (Class 91)",
        "economic_sector": "Information Technology",
        "carbon_intensity_tco2e_per_revenue_million": 0.045,
        "historical_default_loss_rate": 0.012,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "541511",
        "industry_title": "Computer Systems Design and Enterprise Integration Services (Class 92)",
        "economic_sector": "Professional Services",
        "carbon_intensity_tco2e_per_revenue_million": 0.038,
        "historical_default_loss_rate": 0.015,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333122",
        "industry_title": "Construction Machinery & Heavy Equipment Manufacturing (Class 93)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.485,
        "historical_default_loss_rate": 0.035,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333513",
        "industry_title": "Machine Tool (Metal Cutting Types) Precision Manufacturing (Class 94)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.42,
        "historical_default_loss_rate": 0.028,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334414",
        "industry_title": "Printed Circuit Assembly (Electronic Assembly) Manufacturing (Class 95)",
        "economic_sector": "Electronics",
        "carbon_intensity_tco2e_per_revenue_million": 0.28,
        "historical_default_loss_rate": 0.022,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334515",
        "industry_title": "Instruments and Related Products for Measuring Industrial Variables (Class 96)",
        "economic_sector": "Instruments & Optics",
        "carbon_intensity_tco2e_per_revenue_million": 0.19,
        "historical_default_loss_rate": 0.018,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "493116",
        "industry_title": "General Warehousing and Distribution Logistics Storage (Class 97)",
        "economic_sector": "Transportation & Warehousing",
        "carbon_intensity_tco2e_per_revenue_million": 0.35,
        "historical_default_loss_rate": 0.024,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484117",
        "industry_title": "General Freight Trucking, Local Fleet Operations (Class 98)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 0.85,
        "historical_default_loss_rate": 0.042,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484128",
        "industry_title": "General Freight Trucking, Long-Distance Truckload (FTL) (Class 99)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 1.25,
        "historical_default_loss_rate": 0.048,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "423619",
        "industry_title": "Electrical Apparatus and Equipment, Wiring Supplies Wholesalers (Class 100)",
        "economic_sector": "Wholesale Trade",
        "carbon_intensity_tco2e_per_revenue_million": 0.12,
        "historical_default_loss_rate": 0.019,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "511210",
        "industry_title": "Software Publishers & Cloud SaaS Enterprise Platforms (Class 101)",
        "economic_sector": "Information Technology",
        "carbon_intensity_tco2e_per_revenue_million": 0.045,
        "historical_default_loss_rate": 0.012,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "541511",
        "industry_title": "Computer Systems Design and Enterprise Integration Services (Class 102)",
        "economic_sector": "Professional Services",
        "carbon_intensity_tco2e_per_revenue_million": 0.038,
        "historical_default_loss_rate": 0.015,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333122",
        "industry_title": "Construction Machinery & Heavy Equipment Manufacturing (Class 103)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.485,
        "historical_default_loss_rate": 0.035,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333513",
        "industry_title": "Machine Tool (Metal Cutting Types) Precision Manufacturing (Class 104)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.42,
        "historical_default_loss_rate": 0.028,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334414",
        "industry_title": "Printed Circuit Assembly (Electronic Assembly) Manufacturing (Class 105)",
        "economic_sector": "Electronics",
        "carbon_intensity_tco2e_per_revenue_million": 0.28,
        "historical_default_loss_rate": 0.022,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334515",
        "industry_title": "Instruments and Related Products for Measuring Industrial Variables (Class 106)",
        "economic_sector": "Instruments & Optics",
        "carbon_intensity_tco2e_per_revenue_million": 0.19,
        "historical_default_loss_rate": 0.018,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "493116",
        "industry_title": "General Warehousing and Distribution Logistics Storage (Class 107)",
        "economic_sector": "Transportation & Warehousing",
        "carbon_intensity_tco2e_per_revenue_million": 0.35,
        "historical_default_loss_rate": 0.024,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484117",
        "industry_title": "General Freight Trucking, Local Fleet Operations (Class 108)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 0.85,
        "historical_default_loss_rate": 0.042,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484128",
        "industry_title": "General Freight Trucking, Long-Distance Truckload (FTL) (Class 109)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 1.25,
        "historical_default_loss_rate": 0.048,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "423619",
        "industry_title": "Electrical Apparatus and Equipment, Wiring Supplies Wholesalers (Class 110)",
        "economic_sector": "Wholesale Trade",
        "carbon_intensity_tco2e_per_revenue_million": 0.12,
        "historical_default_loss_rate": 0.019,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "511210",
        "industry_title": "Software Publishers & Cloud SaaS Enterprise Platforms (Class 111)",
        "economic_sector": "Information Technology",
        "carbon_intensity_tco2e_per_revenue_million": 0.045,
        "historical_default_loss_rate": 0.012,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "541511",
        "industry_title": "Computer Systems Design and Enterprise Integration Services (Class 112)",
        "economic_sector": "Professional Services",
        "carbon_intensity_tco2e_per_revenue_million": 0.038,
        "historical_default_loss_rate": 0.015,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333122",
        "industry_title": "Construction Machinery & Heavy Equipment Manufacturing (Class 113)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.485,
        "historical_default_loss_rate": 0.035,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "333513",
        "industry_title": "Machine Tool (Metal Cutting Types) Precision Manufacturing (Class 114)",
        "economic_sector": "Industrial Manufacturing",
        "carbon_intensity_tco2e_per_revenue_million": 0.42,
        "historical_default_loss_rate": 0.028,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334414",
        "industry_title": "Printed Circuit Assembly (Electronic Assembly) Manufacturing (Class 115)",
        "economic_sector": "Electronics",
        "carbon_intensity_tco2e_per_revenue_million": 0.28,
        "historical_default_loss_rate": 0.022,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "334515",
        "industry_title": "Instruments and Related Products for Measuring Industrial Variables (Class 116)",
        "economic_sector": "Instruments & Optics",
        "carbon_intensity_tco2e_per_revenue_million": 0.19,
        "historical_default_loss_rate": 0.018,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "493116",
        "industry_title": "General Warehousing and Distribution Logistics Storage (Class 117)",
        "economic_sector": "Transportation & Warehousing",
        "carbon_intensity_tco2e_per_revenue_million": 0.35,
        "historical_default_loss_rate": 0.024,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484117",
        "industry_title": "General Freight Trucking, Local Fleet Operations (Class 118)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 0.85,
        "historical_default_loss_rate": 0.042,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "484128",
        "industry_title": "General Freight Trucking, Long-Distance Truckload (FTL) (Class 119)",
        "economic_sector": "Transportation",
        "carbon_intensity_tco2e_per_revenue_million": 1.25,
        "historical_default_loss_rate": 0.048,
        "is_regulated_audit_sector": True,
    },
    {
        "naics_code": "423619",
        "industry_title": "Electrical Apparatus and Equipment, Wiring Supplies Wholesalers (Class 120)",
        "economic_sector": "Wholesale Trade",
        "carbon_intensity_tco2e_per_revenue_million": 0.12,
        "historical_default_loss_rate": 0.019,
        "is_regulated_audit_sector": True,
    },
]
