"""
SOX 404 IT General Controls (ITGC) & NIST SP 800-53 Rev 5 Audit Catalog.
Standard control objectives, testing procedures, and evidence requirements.
"""

SOX_ITGC_CONTROL_CATALOG = [
    {
        "control_identifier": "AC-01-000",
        "control_title": "Access Control Policy & Procedure (Variant 1)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-001",
        "control_title": "Account Management & Segregation (Variant 2)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-002",
        "control_title": "Access Enforcement & Dual Custody (Variant 3)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-003",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 4)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-004",
        "control_title": "Identification & Multi-Factor Authentication (Variant 5)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-005",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 6)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-006",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 7)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-007",
        "control_title": "Configuration Change Management & Code Review (Variant 8)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-008",
        "control_title": "Information System Backup & Recovery Testing (Variant 9)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-009",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 10)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-010",
        "control_title": "Access Control Policy & Procedure (Variant 11)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-011",
        "control_title": "Account Management & Segregation (Variant 12)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-012",
        "control_title": "Access Enforcement & Dual Custody (Variant 13)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-013",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 14)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-014",
        "control_title": "Identification & Multi-Factor Authentication (Variant 15)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-015",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 16)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-016",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 17)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-017",
        "control_title": "Configuration Change Management & Code Review (Variant 18)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-018",
        "control_title": "Information System Backup & Recovery Testing (Variant 19)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-019",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 20)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-020",
        "control_title": "Access Control Policy & Procedure (Variant 21)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-021",
        "control_title": "Account Management & Segregation (Variant 22)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-022",
        "control_title": "Access Enforcement & Dual Custody (Variant 23)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-023",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 24)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-024",
        "control_title": "Identification & Multi-Factor Authentication (Variant 25)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-025",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 26)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-026",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 27)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-027",
        "control_title": "Configuration Change Management & Code Review (Variant 28)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-028",
        "control_title": "Information System Backup & Recovery Testing (Variant 29)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-029",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 30)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-030",
        "control_title": "Access Control Policy & Procedure (Variant 31)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-031",
        "control_title": "Account Management & Segregation (Variant 32)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-032",
        "control_title": "Access Enforcement & Dual Custody (Variant 33)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-033",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 34)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-034",
        "control_title": "Identification & Multi-Factor Authentication (Variant 35)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-035",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 36)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-036",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 37)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-037",
        "control_title": "Configuration Change Management & Code Review (Variant 38)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-038",
        "control_title": "Information System Backup & Recovery Testing (Variant 39)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-039",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 40)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-040",
        "control_title": "Access Control Policy & Procedure (Variant 41)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-041",
        "control_title": "Account Management & Segregation (Variant 42)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-042",
        "control_title": "Access Enforcement & Dual Custody (Variant 43)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-043",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 44)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-044",
        "control_title": "Identification & Multi-Factor Authentication (Variant 45)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-045",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 46)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-046",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 47)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-047",
        "control_title": "Configuration Change Management & Code Review (Variant 48)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-048",
        "control_title": "Information System Backup & Recovery Testing (Variant 49)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-049",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 50)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-050",
        "control_title": "Access Control Policy & Procedure (Variant 51)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-051",
        "control_title": "Account Management & Segregation (Variant 52)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-052",
        "control_title": "Access Enforcement & Dual Custody (Variant 53)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-053",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 54)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-054",
        "control_title": "Identification & Multi-Factor Authentication (Variant 55)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-055",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 56)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-056",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 57)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-057",
        "control_title": "Configuration Change Management & Code Review (Variant 58)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-058",
        "control_title": "Information System Backup & Recovery Testing (Variant 59)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-059",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 60)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-060",
        "control_title": "Access Control Policy & Procedure (Variant 61)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-061",
        "control_title": "Account Management & Segregation (Variant 62)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-062",
        "control_title": "Access Enforcement & Dual Custody (Variant 63)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-063",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 64)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-064",
        "control_title": "Identification & Multi-Factor Authentication (Variant 65)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-065",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 66)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-066",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 67)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-067",
        "control_title": "Configuration Change Management & Code Review (Variant 68)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-068",
        "control_title": "Information System Backup & Recovery Testing (Variant 69)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-069",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 70)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-070",
        "control_title": "Access Control Policy & Procedure (Variant 71)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-071",
        "control_title": "Account Management & Segregation (Variant 72)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-072",
        "control_title": "Access Enforcement & Dual Custody (Variant 73)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-073",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 74)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-074",
        "control_title": "Identification & Multi-Factor Authentication (Variant 75)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-075",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 76)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-076",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 77)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-077",
        "control_title": "Configuration Change Management & Code Review (Variant 78)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-078",
        "control_title": "Information System Backup & Recovery Testing (Variant 79)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-079",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 80)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-080",
        "control_title": "Access Control Policy & Procedure (Variant 81)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-081",
        "control_title": "Account Management & Segregation (Variant 82)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-082",
        "control_title": "Access Enforcement & Dual Custody (Variant 83)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-083",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 84)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-084",
        "control_title": "Identification & Multi-Factor Authentication (Variant 85)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-085",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 86)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-086",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 87)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-087",
        "control_title": "Configuration Change Management & Code Review (Variant 88)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-088",
        "control_title": "Information System Backup & Recovery Testing (Variant 89)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-089",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 90)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-090",
        "control_title": "Access Control Policy & Procedure (Variant 91)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-091",
        "control_title": "Account Management & Segregation (Variant 92)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-092",
        "control_title": "Access Enforcement & Dual Custody (Variant 93)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-093",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 94)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-094",
        "control_title": "Identification & Multi-Factor Authentication (Variant 95)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-095",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 96)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-096",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 97)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-097",
        "control_title": "Configuration Change Management & Code Review (Variant 98)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-098",
        "control_title": "Information System Backup & Recovery Testing (Variant 99)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-099",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 100)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-100",
        "control_title": "Access Control Policy & Procedure (Variant 101)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-101",
        "control_title": "Account Management & Segregation (Variant 102)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-102",
        "control_title": "Access Enforcement & Dual Custody (Variant 103)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-103",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 104)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-104",
        "control_title": "Identification & Multi-Factor Authentication (Variant 105)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-105",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 106)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-106",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 107)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-107",
        "control_title": "Configuration Change Management & Code Review (Variant 108)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-108",
        "control_title": "Information System Backup & Recovery Testing (Variant 109)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-109",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 110)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-110",
        "control_title": "Access Control Policy & Procedure (Variant 111)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-111",
        "control_title": "Account Management & Segregation (Variant 112)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-112",
        "control_title": "Access Enforcement & Dual Custody (Variant 113)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-113",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 114)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-114",
        "control_title": "Identification & Multi-Factor Authentication (Variant 115)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-115",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 116)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-116",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 117)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-117",
        "control_title": "Configuration Change Management & Code Review (Variant 118)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-118",
        "control_title": "Information System Backup & Recovery Testing (Variant 119)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-119",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 120)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-120",
        "control_title": "Access Control Policy & Procedure (Variant 121)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-121",
        "control_title": "Account Management & Segregation (Variant 122)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-122",
        "control_title": "Access Enforcement & Dual Custody (Variant 123)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-123",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 124)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-124",
        "control_title": "Identification & Multi-Factor Authentication (Variant 125)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-125",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 126)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-126",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 127)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-127",
        "control_title": "Configuration Change Management & Code Review (Variant 128)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-128",
        "control_title": "Information System Backup & Recovery Testing (Variant 129)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-129",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 130)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-130",
        "control_title": "Access Control Policy & Procedure (Variant 131)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-131",
        "control_title": "Account Management & Segregation (Variant 132)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-132",
        "control_title": "Access Enforcement & Dual Custody (Variant 133)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-133",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 134)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-134",
        "control_title": "Identification & Multi-Factor Authentication (Variant 135)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-135",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 136)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-136",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 137)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-137",
        "control_title": "Configuration Change Management & Code Review (Variant 138)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-138",
        "control_title": "Information System Backup & Recovery Testing (Variant 139)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-139",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 140)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-140",
        "control_title": "Access Control Policy & Procedure (Variant 141)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-141",
        "control_title": "Account Management & Segregation (Variant 142)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-142",
        "control_title": "Access Enforcement & Dual Custody (Variant 143)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-143",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 144)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-144",
        "control_title": "Identification & Multi-Factor Authentication (Variant 145)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-145",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 146)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-146",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 147)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-147",
        "control_title": "Configuration Change Management & Code Review (Variant 148)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-148",
        "control_title": "Information System Backup & Recovery Testing (Variant 149)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-149",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 150)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-150",
        "control_title": "Access Control Policy & Procedure (Variant 151)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-151",
        "control_title": "Account Management & Segregation (Variant 152)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-152",
        "control_title": "Access Enforcement & Dual Custody (Variant 153)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-153",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 154)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-154",
        "control_title": "Identification & Multi-Factor Authentication (Variant 155)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-155",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 156)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-156",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 157)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-157",
        "control_title": "Configuration Change Management & Code Review (Variant 158)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-158",
        "control_title": "Information System Backup & Recovery Testing (Variant 159)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-159",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 160)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-160",
        "control_title": "Access Control Policy & Procedure (Variant 161)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-161",
        "control_title": "Account Management & Segregation (Variant 162)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-162",
        "control_title": "Access Enforcement & Dual Custody (Variant 163)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-163",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 164)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-164",
        "control_title": "Identification & Multi-Factor Authentication (Variant 165)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-165",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 166)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-166",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 167)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-167",
        "control_title": "Configuration Change Management & Code Review (Variant 168)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-168",
        "control_title": "Information System Backup & Recovery Testing (Variant 169)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-169",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 170)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-170",
        "control_title": "Access Control Policy & Procedure (Variant 171)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-171",
        "control_title": "Account Management & Segregation (Variant 172)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-172",
        "control_title": "Access Enforcement & Dual Custody (Variant 173)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-173",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 174)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-174",
        "control_title": "Identification & Multi-Factor Authentication (Variant 175)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-175",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 176)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-176",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 177)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-177",
        "control_title": "Configuration Change Management & Code Review (Variant 178)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-178",
        "control_title": "Information System Backup & Recovery Testing (Variant 179)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-179",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 180)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-180",
        "control_title": "Access Control Policy & Procedure (Variant 181)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-181",
        "control_title": "Account Management & Segregation (Variant 182)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-182",
        "control_title": "Access Enforcement & Dual Custody (Variant 183)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-183",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 184)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-184",
        "control_title": "Identification & Multi-Factor Authentication (Variant 185)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-185",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 186)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-186",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 187)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-187",
        "control_title": "Configuration Change Management & Code Review (Variant 188)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-188",
        "control_title": "Information System Backup & Recovery Testing (Variant 189)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-189",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 190)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-01-190",
        "control_title": "Access Control Policy & Procedure (Variant 191)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Annual review and approval of logical and physical access control policy documents.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-02-191",
        "control_title": "Account Management & Segregation (Variant 192)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Automated provisioning/deprovisioning of ERP accounts via SCIM and SSO SAML.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-03-192",
        "control_title": "Access Enforcement & Dual Custody (Variant 193)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Role-based access control (RBAC) preventing unauthorized ledger postings and payments.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AC-06-193",
        "control_title": "Least Privilege Principle & Periodic Review (Variant 194)",
        "control_domain": "ACCESS_CONTROL",
        "risk_severity": "HIGH",
        "control_objective_description": "Quarterly user access certification by department heads for superuser privileges.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "IA-02-194",
        "control_title": "Identification & Multi-Factor Authentication (Variant 195)",
        "control_domain": "AUTHENTICATION",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Mandatory FIDO2 / WebAuthn hardware token MFA for all administrative and financial actions.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-02-195",
        "control_title": "Event Logging & Immutable Audit Trail (Variant 196)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Append-only cryptographic tamper-evident logging of all financial mutations and data exports.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "AU-06-196",
        "control_title": "Audit Review, Analysis, and Anomaly Reporting (Variant 197)",
        "control_domain": "AUDIT_LOGGING",
        "risk_severity": "HIGH",
        "control_objective_description": "Continuous automated monitoring of high-risk transactions with SIEM integration.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CM-03-197",
        "control_title": "Configuration Change Management & Code Review (Variant 198)",
        "control_domain": "CHANGE_MANAGEMENT",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Segregated deployment pipelines requiring peer review and automated CI test validation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "CP-09-198",
        "control_title": "Information System Backup & Recovery Testing (Variant 199)",
        "control_domain": "CONTINGENCY_PLANNING",
        "risk_severity": "HIGH",
        "control_objective_description": "Daily automated encrypted database snapshots with semi-annual point-in-time recovery audits.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
    {
        "control_identifier": "SC-13-199",
        "control_title": "Cryptographic Protection & Key Rotation (Variant 200)",
        "control_domain": "CRYPTOGRAPHY",
        "risk_severity": "CRITICAL",
        "control_objective_description": "Envelope encryption using AES-256-GCM and annual KMS master key rotation.",
        "testing_frequency": "QUARTERLY",
        "is_key_sox_control": True,
    },
]
