"""
50-State Statutory Economic Nexus & Wayfair Sales Tax Reference Tables.
"""

STATE_TAX_NEXUS_STATUTORY_TABLES = [
    {
        "state_code": "AL",
        "state_name": "Alabama",
        "revenue_threshold_usd": 250000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2018-10-01",
        "state_base_sales_tax_rate": 0.04,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "AK",
        "state_name": "Alaska (Local Only)",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2020-01-01",
        "state_base_sales_tax_rate": 0.0,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "AZ",
        "state_name": "Arizona",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2019-10-01",
        "state_base_sales_tax_rate": 0.056,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "AR",
        "state_name": "Arkansas",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2019-07-01",
        "state_base_sales_tax_rate": 0.065,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "CA",
        "state_name": "California",
        "revenue_threshold_usd": 500000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2019-04-01",
        "state_base_sales_tax_rate": 0.0725,
        "tax_sourcing_rule": "Modified Origin",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "CO",
        "state_name": "Colorado",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2018-12-01",
        "state_base_sales_tax_rate": 0.029,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "CT",
        "state_name": "Connecticut",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2018-12-01",
        "state_base_sales_tax_rate": 0.0635,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "DE",
        "state_name": "Delaware",
        "revenue_threshold_usd": 0.0,
        "transaction_count_threshold": 0,
        "effective_date": "N/A - No Sales Tax",
        "state_base_sales_tax_rate": 0.0,
        "tax_sourcing_rule": "None",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "FL",
        "state_name": "Florida",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2021-07-01",
        "state_base_sales_tax_rate": 0.06,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "GA",
        "state_name": "Georgia",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2019-01-01",
        "state_base_sales_tax_rate": 0.04,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "HI",
        "state_name": "Hawaii (GET)",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2018-07-01",
        "state_base_sales_tax_rate": 0.04,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "ID",
        "state_name": "Idaho",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2019-06-01",
        "state_base_sales_tax_rate": 0.06,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "IL",
        "state_name": "Illinois",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2018-10-01",
        "state_base_sales_tax_rate": 0.0625,
        "tax_sourcing_rule": "Origin/Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "IN",
        "state_name": "Indiana",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2018-10-01",
        "state_base_sales_tax_rate": 0.07,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "IA",
        "state_name": "Iowa",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2019-01-01",
        "state_base_sales_tax_rate": 0.06,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "KS",
        "state_name": "Kansas",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2021-07-01",
        "state_base_sales_tax_rate": 0.065,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "KY",
        "state_name": "Kentucky",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2018-10-01",
        "state_base_sales_tax_rate": 0.06,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "LA",
        "state_name": "Louisiana",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2020-07-01",
        "state_base_sales_tax_rate": 0.0445,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "ME",
        "state_name": "Maine",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2018-07-01",
        "state_base_sales_tax_rate": 0.055,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "MD",
        "state_name": "Maryland",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2018-10-01",
        "state_base_sales_tax_rate": 0.06,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "MA",
        "state_name": "Massachusetts",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2019-10-01",
        "state_base_sales_tax_rate": 0.0625,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "MI",
        "state_name": "Michigan",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2018-10-01",
        "state_base_sales_tax_rate": 0.06,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "MN",
        "state_name": "Minnesota",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2018-10-01",
        "state_base_sales_tax_rate": 0.06875,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "MS",
        "state_name": "Mississippi",
        "revenue_threshold_usd": 250000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2018-09-01",
        "state_base_sales_tax_rate": 0.07,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "MO",
        "state_name": "Missouri",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2023-01-01",
        "state_base_sales_tax_rate": 0.04225,
        "tax_sourcing_rule": "Origin",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "MT",
        "state_name": "Montana",
        "revenue_threshold_usd": 0.0,
        "transaction_count_threshold": 0,
        "effective_date": "N/A - No Sales Tax",
        "state_base_sales_tax_rate": 0.0,
        "tax_sourcing_rule": "None",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "NE",
        "state_name": "Nebraska",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2019-01-01",
        "state_base_sales_tax_rate": 0.055,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "NV",
        "state_name": "Nevada",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2018-10-01",
        "state_base_sales_tax_rate": 0.0685,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "NH",
        "state_name": "New Hampshire",
        "revenue_threshold_usd": 0.0,
        "transaction_count_threshold": 0,
        "effective_date": "N/A - No Sales Tax",
        "state_base_sales_tax_rate": 0.0,
        "tax_sourcing_rule": "None",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "NJ",
        "state_name": "New Jersey",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2018-11-01",
        "state_base_sales_tax_rate": 0.06625,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "NM",
        "state_name": "New Mexico (Gross Receipts)",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2019-07-01",
        "state_base_sales_tax_rate": 0.05125,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "NY",
        "state_name": "New York",
        "revenue_threshold_usd": 500000.0,
        "transaction_count_threshold": 100,
        "effective_date": "2018-06-21",
        "state_base_sales_tax_rate": 0.04,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "NC",
        "state_name": "North Carolina",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2018-11-01",
        "state_base_sales_tax_rate": 0.0475,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "ND",
        "state_name": "North Dakota",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2018-10-01",
        "state_base_sales_tax_rate": 0.05,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "OH",
        "state_name": "Ohio",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2019-08-01",
        "state_base_sales_tax_rate": 0.0575,
        "tax_sourcing_rule": "Origin/Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "OK",
        "state_name": "Oklahoma",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2019-11-01",
        "state_base_sales_tax_rate": 0.045,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "OR",
        "state_name": "Oregon",
        "revenue_threshold_usd": 0.0,
        "transaction_count_threshold": 0,
        "effective_date": "N/A - No Sales Tax",
        "state_base_sales_tax_rate": 0.0,
        "tax_sourcing_rule": "None",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "PA",
        "state_name": "Pennsylvania",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2019-07-01",
        "state_base_sales_tax_rate": 0.06,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "RI",
        "state_name": "Rhode Island",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2019-07-01",
        "state_base_sales_tax_rate": 0.07,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "SC",
        "state_name": "South Carolina",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2018-11-01",
        "state_base_sales_tax_rate": 0.06,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "SD",
        "state_name": "South Dakota",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2018-11-01",
        "state_base_sales_tax_rate": 0.045,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "TN",
        "state_name": "Tennessee",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2020-10-01",
        "state_base_sales_tax_rate": 0.07,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "TX",
        "state_name": "Texas",
        "revenue_threshold_usd": 500000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2019-10-01",
        "state_base_sales_tax_rate": 0.0625,
        "tax_sourcing_rule": "Origin/Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "UT",
        "state_name": "Utah",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2019-01-01",
        "state_base_sales_tax_rate": 0.061,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "VT",
        "state_name": "Vermont",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2018-07-01",
        "state_base_sales_tax_rate": 0.06,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "VA",
        "state_name": "Virginia",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2019-07-01",
        "state_base_sales_tax_rate": 0.053,
        "tax_sourcing_rule": "Origin/Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "WA",
        "state_name": "Washington",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2018-10-01",
        "state_base_sales_tax_rate": 0.065,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "WV",
        "state_name": "West Virginia",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2019-01-01",
        "state_base_sales_tax_rate": 0.06,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "WI",
        "state_name": "Wisconsin",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 0,
        "effective_date": "2018-10-01",
        "state_base_sales_tax_rate": 0.05,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
    {
        "state_code": "WY",
        "state_name": "Wyoming",
        "revenue_threshold_usd": 100000.0,
        "transaction_count_threshold": 200,
        "effective_date": "2019-02-01",
        "state_base_sales_tax_rate": 0.04,
        "tax_sourcing_rule": "Destination",
        "has_local_option_taxes": True,
    },
]
