"""
Field Service Enums.
"""
import enum

class FieldWorkOrderStatus(str, enum.Enum):
    UNASSIGNED = "UNASSIGNED"
    DISPATCHED = "DISPATCHED"
    EN_ROUTE = "EN_ROUTE"
    ON_SITE_IN_PROGRESS = "ON_SITE_IN_PROGRESS"
    PENDING_PARTS = "PENDING_PARTS"
    COMPLETED_PENDING_SIGNATURE = "COMPLETED_PENDING_SIGNATURE"
    CLOSED_RESOLVED = "CLOSED_RESOLVED"

class WorkOrderPriority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    EMERGENCY_CRITICAL = "EMERGENCY_CRITICAL"

class SLASeverityTier(str, enum.Enum):
    P1_FOUR_HOUR_ONSITE = "P1_FOUR_HOUR_ONSITE"
    P2_NEXT_BUSINESS_DAY = "P2_NEXT_BUSINESS_DAY"
    P3_STANDARD_PLANNED = "P3_STANDARD_PLANNED"
