"""
Vendor Collaboration Portal Enums.
"""
import enum

class ASNStatus(str, enum.Enum):
    TRANSMITTED = "TRANSMITTED"
    GEOFENCE_ARRIVED = "GEOFENCE_ARRIVED"
    DOCK_UNLOADED = "DOCK_UNLOADED"
    RECEIVING_VERIFIED = "RECEIVING_VERIFIED"
    DISCREPANCY_FLAGGED = "DISCREPANCY_FLAGGED"

class SupplierOnboardingState(str, enum.Enum):
    REGISTRATION_INVITED = "REGISTRATION_INVITED"
    TAX_W9_SUBMITTED = "TAX_W9_SUBMITTED"
    BANK_DETAILS_VERIFIED = "BANK_DETAILS_VERIFIED"
    COMPLIANCE_APPROVED = "COMPLIANCE_APPROVED"
    ACTIVE_SUPPLIER = "ACTIVE_SUPPLIER"
