import React, { useEffect, useState } from 'react';
import { BarChart3, CalendarDays, DollarSign, Plus, RefreshCw, Search, Target, X } from 'lucide-react';
import api from '../services/api';

type Opportunity = { id: string; opportunity_number: string; name: string; stage_code: string; amount: string; probability_percent: number; expected_close_date?: string; status: string; next_step?: string };
const stages = ['QUALIFICATION', 'DISCOVERY', 'PROPOSAL', 'COMMIT', 'CLOSED_WON'];
const stageLabels: Record<string, string> = { QUALIFICATION: 'Qualification', DISCOVERY: 'Discovery', PROPOSAL: 'Proposal', COMMIT: 'Commit', CLOSED_WON: 'Won' };

export const CRM: React.FC = () => {
  const [opportunities, setOpportunities] = useState<Opportunity[]>([]);
  const [stage, setStage] = useState('');
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);
  const [showCreate, setShowCreate] = useState(false);
  const [name, setName] = useState('');
  const [amount, setAmount] = useState('');
  const [probability, setProbability] = useState('20');
  const [closeDate, setCloseDate] = useState('');

  const load = async () => { setLoading(true); const response = await api.get('/sales/opportunities', { params: stage ? { stage_code: stage } : {} }); setOpportunities(response.data); setLoading(false); };
  useEffect(() => { void load(); }, [stage]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); await api.post('/sales/opportunities', { name, amount: Number(amount || 0), probability_percent: Number(probability), expected_close_date: closeDate || undefined, stage_code: 'QUALIFICATION' }); setName(''); setAmount(''); setProbability('20'); setCloseDate(''); setShowCreate(false); await load(); };
  const visible = opportunities.filter(item => `${item.opportunity_number} ${item.name}`.toLowerCase().includes(search.toLowerCase()));
  const pipeline = visible.reduce((sum, item) => sum + Number(item.amount), 0);
  const weighted = visible.reduce((sum, item) => sum + Number(item.amount) * item.probability_percent / 100, 0);

  return <main className="min-h-full bg-slate-950 px-5 py-6 text-slate-100 lg:px-8">
    <header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-amber-400"><Target size={14} /> Revenue operations</div><h1 className="text-3xl font-semibold tracking-tight">Opportunity pipeline</h1><p className="mt-1 text-sm text-slate-400">Turn customer conversations into a forecast your team can trust.</p></div><div className="flex gap-2"><button onClick={() => void load()} title="Refresh pipeline" className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-300 hover:border-amber-500"><RefreshCw size={16} /> Refresh</button><button onClick={() => setShowCreate(true)} className="inline-flex items-center gap-2 rounded-lg bg-amber-400 px-3 py-2 text-sm font-semibold text-slate-950 hover:bg-amber-300"><Plus size={16} /> New opportunity</button></div></header>
    <section className="mb-7 grid grid-cols-1 gap-3 sm:grid-cols-3"><Metric icon={<DollarSign size={17} />} label="Pipeline value" value={`$${pipeline.toLocaleString(undefined, { maximumFractionDigits: 0 })}`} color="text-amber-300" /><Metric icon={<BarChart3 size={17} />} label="Weighted forecast" value={`$${weighted.toLocaleString(undefined, { maximumFractionDigits: 0 })}`} color="text-emerald-300" /><Metric icon={<CalendarDays size={17} />} label="Open opportunities" value={String(visible.length)} color="text-cyan-300" /></section>
    <section className="border border-slate-800 bg-slate-900/70"><div className="flex flex-wrap gap-3 border-b border-slate-800 p-4"><div className="relative min-w-[240px] flex-1"><Search size={16} className="absolute left-3 top-2.5 text-slate-500" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search opportunities" className="w-full rounded-lg border border-slate-700 bg-slate-950 py-2 pl-9 pr-3 text-sm outline-none focus:border-amber-400" /></div><select value={stage} onChange={event => setStage(event.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-300 outline-none"><option value="">All stages</option>{stages.map(item => <option key={item} value={item}>{stageLabels[item]}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-950/70 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Opportunity</th><th className="px-4 py-3">Stage</th><th className="px-4 py-3">Close date</th><th className="px-4 py-3 text-right">Probability</th><th className="px-4 py-3 text-right">Amount</th></tr></thead><tbody className="divide-y divide-slate-800">{loading ? <tr><td colSpan={5} className="p-12 text-center text-slate-500">Loading pipeline...</td></tr> : visible.map(item => <tr key={item.id} className="hover:bg-slate-800/40"><td className="px-4 py-4"><div className="font-medium">{item.name}</div><div className="mt-1 text-xs text-slate-500">{item.opportunity_number}</div></td><td className="px-4 py-4 text-slate-300">{stageLabels[item.stage_code] || item.stage_code}</td><td className="px-4 py-4 text-slate-400">{item.expected_close_date || 'Unscheduled'}</td><td className="px-4 py-4 text-right text-slate-300">{item.probability_percent}%</td><td className="px-4 py-4 text-right font-medium text-amber-300">${Number(item.amount).toLocaleString()}</td></tr>)}</tbody></table></div></section>
    {showCreate && <div className="fixed inset-0 z-20 flex items-center justify-center bg-slate-950/80 p-4"><form onSubmit={create} className="w-full max-w-lg border border-slate-700 bg-slate-900 p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">New opportunity</h2><button type="button" onClick={() => setShowCreate(false)} aria-label="Close"><X size={18} /></button></div><Field label="Opportunity name" value={name} setValue={setName} required /><Field label="Amount" value={amount} setValue={setAmount} type="number" required /><Field label="Probability percent" value={probability} setValue={setProbability} type="number" required /><Field label="Expected close date" value={closeDate} setValue={setCloseDate} type="date" /><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setShowCreate(false)} className="rounded-lg border border-slate-700 px-4 py-2 text-sm">Cancel</button><button type="submit" className="rounded-lg bg-amber-400 px-4 py-2 text-sm font-semibold text-slate-950">Create opportunity</button></div></form></div>}
  </main>;
};
const Field: React.FC<{ label: string; value: string; setValue: (value: string) => void; type?: string; required?: boolean }> = ({ label, value, setValue, type = 'text', required }) => <label className="mb-4 block text-sm text-slate-300">{label}<input type={type} value={value} onChange={event => setValue(event.target.value)} required={required} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 outline-none focus:border-amber-400" /></label>;
const Metric: React.FC<{ icon: React.ReactNode; label: string; value: string; color: string }> = ({ icon, label, value, color }) => <div className="border border-slate-800 bg-slate-900/70 p-4"><div className={`mb-3 flex items-center gap-2 text-xs uppercase tracking-wider ${color}`}>{icon}{label}</div><div className="text-2xl font-semibold tabular-nums">{value}</div></div>;
