import React, { useEffect, useState } from 'react';
import { Bell, Check, RefreshCw, ShieldAlert } from 'lucide-react';
import api from '../services/api';

type NotificationRecord = { id: string; title: string; message: string; severity: string; entity_type?: string; entity_id?: string; is_read: boolean; created_at: string };
const severityColor: Record<string, string> = { INFO: 'border-cyan-800 text-cyan-300', SUCCESS: 'border-emerald-800 text-emerald-300', WARNING: 'border-amber-800 text-amber-300', ERROR: 'border-rose-800 text-rose-300', CRITICAL: 'border-rose-500 text-rose-200' };

export const Notifications: React.FC = () => {
  const [items, setItems] = useState<NotificationRecord[]>([]);
  const [unreadOnly, setUnreadOnly] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const response = await api.get('/workflow-automation/notifications', { params: { unread_only: unreadOnly } }); setItems(response.data); } catch { setError('Notifications could not be loaded.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [unreadOnly]);
  const markRead = async (id: string) => { await api.patch(`/workflow-automation/notifications/${id}`, { is_read: true }); await load(); };
  return <main className="min-h-full bg-slate-950 px-5 py-6 text-slate-100 lg:px-8"><header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-cyan-400"><Bell size={14} /> Operations center</div><h1 className="text-3xl font-semibold tracking-tight">Notifications</h1><p className="mt-1 text-sm text-slate-400">Actionable updates from finance, service, manufacturing, and supply operations.</p></div><button onClick={() => void load()} title="Refresh notifications" className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-300 hover:border-cyan-500"><RefreshCw size={16} /> Refresh</button></header><div className="mb-5 flex items-center justify-between border-b border-slate-800 pb-3"><span className="text-sm text-slate-400">{items.length} notifications</span><label className="flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" checked={unreadOnly} onChange={event => setUnreadOnly(event.target.checked)} /> Unread only</label></div>{error && <div className="mb-4 border border-rose-900 bg-rose-950/40 px-4 py-3 text-sm text-rose-200"><ShieldAlert className="mr-2 inline" size={16} />{error}</div>}<section className="space-y-3">{loading ? <div className="py-12 text-center text-slate-500">Loading notifications...</div> : items.length === 0 ? <div className="border border-slate-800 py-12 text-center text-slate-500">You are all caught up.</div> : items.map(item => <article key={item.id} className={`border bg-slate-900/70 p-4 ${severityColor[item.severity] || 'border-slate-800 text-slate-300'}`}><div className="flex items-start justify-between gap-4"><div><h2 className="font-medium text-slate-100">{item.title}</h2><p className="mt-1 text-sm text-slate-400">{item.message}</p><time className="mt-3 block text-xs text-slate-500">{new Date(item.created_at).toLocaleString()}</time></div>{item.is_read ? <Check size={18} className="text-emerald-400" /> : <button onClick={() => void markRead(item.id)} title="Mark as read" className="rounded p-1 text-slate-400 hover:bg-slate-800 hover:text-emerald-300"><Check size={18} /></button>}</div></article>)}</section></main>;
};
