"""
CRM & CPQ Enums.
"""
import enum

class LeadSource(str, enum.Enum):
    ORGANIC_WEB = "ORGANIC_WEB"
    PAID_CAMPAIGN = "PAID_CAMPAIGN"
    TRADE_SHOW = "TRADE_SHOW"
    PARTNER_REFERRAL = "PARTNER_REFERRAL"
    OUTBOUND_COLD = "OUTBOUND_COLD"
    INBOUND_API = "INBOUND_API"

class LeadQualificationStatus(str, enum.Enum):
    NEW_UNTOUCHED = "NEW_UNTOUCHED"
    CONTACTED = "CONTACTED"
    MARKETING_QUALIFIED = "MARKETING_QUALIFIED"
    SALES_QUALIFIED = "SALES_QUALIFIED"
    CONVERTED = "CONVERTED"
    DISQUALIFIED = "DISQUALIFIED"

class OpportunityDealStage(str, enum.Enum):
    PROSPECTING = "PROSPECTING"
    NEEDS_ANALYSIS = "NEEDS_ANALYSIS"
    PROPOSAL_CPQ_QUOTE = "PROPOSAL_CPQ_QUOTE"
    NEGOTIATION_REVIEW = "NEGOTIATION_REVIEW"
    CLOSED_WON = "CLOSED_WON"
    CLOSED_LOST = "CLOSED_LOST"

class CPQDiscountType(str, enum.Enum):
    PERCENTAGE = "PERCENTAGE"
    FIXED_AMOUNT = "FIXED_AMOUNT"
    VOLUME_TIERED = "VOLUME_TIERED"
