"""
Contract Lifecycle Management Enums.
"""
import enum

class ContractType(str, enum.Enum):
    MASTER_SERVICES_AGREEMENT = "MASTER_SERVICES_AGREEMENT"
    NON_DISCLOSURE_AGREEMENT = "NON_DISCLOSURE_AGREEMENT"
    STATEMENT_OF_WORK = "STATEMENT_OF_WORK"
    SOFTWARE_LICENSE_SLA = "SOFTWARE_LICENSE_SLA"
    VENDOR_SUPPLY_CONTRACT = "VENDOR_SUPPLY_CONTRACT"
    EMPLOYMENT_EXECUTIVE = "EMPLOYMENT_EXECUTIVE"

class ContractStatus(str, enum.Enum):
    DRAFT_AUTHORING = "DRAFT_AUTHORING"
    INTERNAL_LEGAL_REVIEW = "INTERNAL_LEGAL_REVIEW"
    OUT_FOR_SIGNATURE = "OUT_FOR_SIGNATURE"
    ACTIVE_EXECUTED = "ACTIVE_EXECUTED"
    AMENDMENT_IN_PROGRESS = "AMENDMENT_IN_PROGRESS"
    EXPIRED = "EXPIRED"
    TERMINATED = "TERMINATED"

class RenewalType(str, enum.Enum):
    EVERGREEN_AUTO_RENEW = "EVERGREEN_AUTO_RENEW"
    FIXED_TERM_MANUAL_RENEW = "FIXED_TERM_MANUAL_RENEW"
    ONE_TIME_NO_RENEW = "ONE_TIME_NO_RENEW"
