"""
Fixed Assets Management Enums.
"""
import enum

class AssetCategory(str, enum.Enum):
    BUILDINGS_PROPERTY = "BUILDINGS_PROPERTY"
    MACHINERY_EQUIPMENT = "MACHINERY_EQUIPMENT"
    VEHICLES = "VEHICLES"
    IT_HARDWARE = "IT_HARDWARE"
    SOFTWARE_INTANGIBLES = "SOFTWARE_INTANGIBLES"
    FURNITURE_FIXTURES = "FURNITURE_FIXTURES"
    LEASEHOLD_IMPROVEMENTS = "LEASEHOLD_IMPROVEMENTS"

class DepreciationMethod(str, enum.Enum):
    STRAIGHT_LINE = "STRAIGHT_LINE"
    DECLINING_BALANCE = "DECLINING_BALANCE"
    DOUBLE_DECLINING_BALANCE = "DOUBLE_DECLINING_BALANCE"
    SUM_OF_YEARS_DIGITS = "SUM_OF_YEARS_DIGITS"
    MACRS_200 = "MACRS_200"
    UNITS_OF_PRODUCTION = "UNITS_OF_PRODUCTION"

class AssetStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    CIP_WORK_IN_PROGRESS = "CIP_WORK_IN_PROGRESS"
    ACTIVE_IN_SERVICE = "ACTIVE_IN_SERVICE"
    FULLY_DEPRECIATED = "FULLY_DEPRECIATED"
    UNDER_MAINTENANCE = "UNDER_MAINTENANCE"
    IMPAIRED = "IMPAIRED"
    RETIRED_DISPOSED = "RETIRED_DISPOSED"
